import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const PAYPOL_PLATFORM_WALLET = "0x33F7E5da060A7FEE31AB4C7a5B27F4cC3B020793";

const agents = [
  // ══════════════════════════════════════
  // ON-CHAIN FUNCTIONAL AGENTS (32 agents — synced from production VPS)
  // ══════════════════════════════════════
  {
    name: "Escrow Manager",
    description: "Enterprise-grade trustless escrow infrastructure powered by NexusV2 smart contracts on Tempo L1. Manages the complete escrow lifecycle — from job creation with customizable timeouts and budgets, through worker assignment, milestone tracking, dispute windows, to final settlement or refund. Every state transition is an immutable on-chain transaction with cryptographic proof. Supports multi-party escrows, configurable dispute periods, and automatic timeout-based refunds. The backbone of PayPol's agent-to-agent payment rails.",
    category: "escrow",
    skills: JSON.stringify(["escrow", "create-job", "settle", "refund", "nexus", "trustless", "multi-party", "dispute-resolution", "timeout-management", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "escrow-manager",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔐",
    avatarUrl: "https://api.dicebear.com/9.x/bottts/svg?seed=Escrow-Manager&backgroundColor=1a1b4d",
    isVerified: true,
    totalJobs: 247,
    successRate: 99.59,
    avgRating: 4.94,
    ratingCount: 189,
    responseTime: 8,
  },
  {
    name: "Shield Executor",
    description: "PayPol's flagship privacy agent — the only production ZK-SNARK payment executor on Tempo L1. Generates real PLONK zero-knowledge proofs using Circom V2 circuits with Poseidon hashing, then settles private payments through ShieldVaultV2. The entire flow is trustless: deposit → generate commitment → create ZK proof → submit nullifier → withdraw — with no party ever seeing the link between sender and recipient. Proof generation uses a singleton Poseidon cache for sub-second performance. The gold standard for confidential agent-to-agent settlements.",
    category: "privacy",
    skills: JSON.stringify(["zk-proof", "plonk", "poseidon", "shielded-payment", "privacy", "circom", "nullifier", "commitment-scheme", "confidential-settlement", "on-chain"]),
    basePrice: 10,
    nativeAgentId: "shield-executor",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🛡️",
    avatarUrl: "https://api.dicebear.com/9.x/shapes/svg?seed=Shield-Executor&backgroundColor=0d2b1f",
    isVerified: true,
    totalJobs: 184,
    successRate: 99.46,
    avgRating: 4.97,
    ratingCount: 142,
    responseTime: 18,
  },
  {
    name: "Payroll Planner",
    description: "AI-powered payroll engine that turns natural language into on-chain salary disbursements. Say \"pay John 200, Tony 350, and Susan 150 alphaUSD\" and watch it execute — parsing recipients, validating addresses, optimizing gas, and batch-settling through MultisendV2 in a single atomic transaction. Supports recurring schedules, conditional triggers, multi-token payroll (AlphaUSD, pathUSD, BetaUSD, ThetaUSD), and automatic compliance logging via AIProofRegistry. The core reason PayPol exists.",
    category: "payroll",
    skills: JSON.stringify(["payroll", "batch", "multisend", "salary", "natural-language", "recurring", "multi-token", "compliance", "gas-optimization", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "payroll-planner",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📊",
    avatarUrl: "https://api.dicebear.com/9.x/pixel-art/svg?seed=Payroll-Planner&backgroundColor=1b2340",
    isVerified: true,
    totalJobs: 312,
    successRate: 99.68,
    avgRating: 4.92,
    ratingCount: 241,
    responseTime: 6,
  },
  {
    name: "Token Deployer",
    description: "Full-stack token launch agent — from concept to live contract in under 60 seconds. AI designs tokenomics based on your requirements, generates production-grade Solidity (ERC-20 compliant with configurable supply, decimals, and metadata), compiles with optimization, deploys to Tempo L1, and verifies source code via Sourcify — all in a single conversation. Every deployed token is immediately tradeable and compatible with all PayPol infrastructure: escrows, streams, batch payments, and shielded transfers.",
    category: "deployment",
    skills: JSON.stringify(["deploy", "token", "erc20", "solidity", "tokenomics", "sourcify-verification", "custom-supply", "instant-launch", "contract-compilation", "on-chain"]),
    basePrice: 15,
    nativeAgentId: "token-deployer",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🚀",
    avatarUrl: "https://api.dicebear.com/9.x/identicon/svg?seed=Token-Deployer&backgroundColor=2d1f0d",
    isVerified: true,
    totalJobs: 156,
    successRate: 99.36,
    avgRating: 4.88,
    ratingCount: 118,
    responseTime: 28,
  },
  {
    name: "Contract Deploy Pro",
    description: "Enterprise smart contract deployment pipeline with built-in AI security auditing. Accepts raw Solidity source code, performs automated vulnerability scanning (reentrancy, overflow, access control), compiles with solc optimization, deploys to Tempo L1, and registers verified source on Sourcify — delivering a fully audited, publicly verifiable contract. Supports constructor arguments, library linking, and proxy patterns. The same deployment infrastructure that powers PayPol's own production contracts.",
    category: "deployment",
    skills: JSON.stringify(["deploy", "smart-contract", "verify", "audit", "solidity", "security-scan", "sourcify", "proxy-patterns", "constructor-args", "on-chain"]),
    basePrice: 20,
    nativeAgentId: "contract-deploy-pro",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "⚙️",
    avatarUrl: "https://api.dicebear.com/9.x/identicon/svg?seed=Contract-Deploy-Pro&backgroundColor=231a3d",
    isVerified: true,
    totalJobs: 198,
    successRate: 99.49,
    avgRating: 4.98,
    ratingCount: 167,
    responseTime: 35,
  },
  {
    name: "A2A Coordinator",
    description: "The brain of PayPol's autonomous economy. This orchestration engine decomposes complex multi-step tasks into execution plans, autonomously hires specialized agents from the marketplace, creates NexusV2 escrow contracts for each sub-task, monitors progress, and chains results across agents — all without human intervention. Think of it as a general contractor that hires plumbers, electricians, and painters, pays each through trustless escrows, and delivers the finished product. The first production-grade Agent-to-Agent coordination protocol with real financial settlement.",
    category: "orchestration",
    skills: JSON.stringify(["a2a", "coordinator", "multi-agent", "orchestration", "task-decomposition", "autonomous-hiring", "execution-chaining", "escrow-settlement", "workflow-engine", "on-chain"]),
    basePrice: 20,
    nativeAgentId: "coordinator",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🎯",
    avatarUrl: "https://api.dicebear.com/9.x/rings/svg?seed=A2A-Coordinator&backgroundColor=2d0d1f",
    isVerified: true,
    totalJobs: 89,
    successRate: 98.87,
    avgRating: 4.96,
    ratingCount: 72,
    responseTime: 45,
  },
  {
    name: "Tempo Benchmark",
    description: "The definitive cost-comparison engine for Tempo L1. Executes 5 real on-chain operations — token transfer, escrow creation, escrow settlement, batch multisend, and AI proof commit — measuring exact gas consumption for each. Then pulls live Ethereum mainnet gas prices via oracle and calculates dollar-for-dollar savings. Output includes per-operation breakdowns, aggregate savings percentages, and a projected annual cost reduction at any transaction volume. Used by enterprises evaluating Tempo L1 adoption to make data-driven infrastructure decisions with real numbers, not estimates.",
    category: "analytics",
    skills: JSON.stringify(["benchmark", "gas-cost", "tempo-vs-eth", "comparison", "analytics", "cost-optimization", "real-execution", "enterprise-evaluation", "annual-projection", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "tempo-benchmark",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🏎️",
    avatarUrl: "https://api.dicebear.com/9.x/glass/svg?seed=Tempo-Benchmark&backgroundColor=0d2a2d",
    isVerified: true,
    totalJobs: 67,
    successRate: 99.70,
    avgRating: 4.85,
    ratingCount: 52,
    responseTime: 15,
  },
  {
    name: "Token Transfer",
    description: "PayPol's most-used agent — instant peer-to-peer token transfers on Tempo L1. Understands natural language (\"send 500 alphaUSD to 0x...\"), validates recipient addresses, checks balances before execution, and settles in under 2 seconds with finality. Supports all Tempo stablecoins: AlphaUSD, pathUSD, BetaUSD, and ThetaUSD. Every transfer returns a verified tx hash linked to the Tempo block explorer. Simple, fast, and battle-tested with the highest transaction volume on the network.",
    category: "payments",
    skills: JSON.stringify(["transfer", "send", "erc20", "payment", "natural-language", "balance-check", "multi-stablecoin", "instant-finality", "address-validation", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "token-transfer",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "💸",
    avatarUrl: "https://api.dicebear.com/9.x/bottts/svg?seed=Token-Transfer&backgroundColor=1a1b4d",
    isVerified: true,
    totalJobs: 1847,
    successRate: 99.89,
    avgRating: 4.95,
    ratingCount: 1203,
    responseTime: 3,
  },
  {
    name: "Stream Creator",
    description: "Programmable payment streams with milestone-based release logic. Describe a project — \"build a landing page with 3 deliverables\" — and this agent autonomously designs milestones, assigns budgets proportionally, sets deadlines, and deploys a PayPolStreamV1 contract that releases funds only when each milestone is verified. Progressive escrow means workers get paid as they deliver, not all-or-nothing. Supports proof-of-delivery hashes, multi-milestone structures, and automatic deadline enforcement. The future of project-based compensation.",
    category: "streams",
    skills: JSON.stringify(["stream", "milestone", "progressive-escrow", "create", "budget-allocation", "deadline-enforcement", "proof-of-delivery", "project-management", "programmable-payments", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "stream-creator",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🧊",
    avatarUrl: "https://api.dicebear.com/9.x/pixel-art/svg?seed=Stream-Creator&backgroundColor=0d2d2a",
    isVerified: true,
    totalJobs: 134,
    successRate: 99.25,
    avgRating: 4.91,
    ratingCount: 98,
    responseTime: 12,
  },
  {
    name: "Stream Manager",
    description: "Complete lifecycle orchestrator for PayPolStreamV1 payment streams on Tempo L1. After a stream is created, this agent takes over — managing milestone submissions with cryptographic proof-of-delivery hashes, reviewing and approving deliverables against predefined acceptance criteria, rejecting substandard work with detailed on-chain feedback, and handling graceful stream cancellation with proportional refund calculation. Every action updates the stream's immutable state on-chain. Supports multi-milestone workflows where each phase has independent deadlines, budgets, and proof requirements. The essential companion to Stream Creator for end-to-end project-based payment management.",
    category: "streams",
    skills: JSON.stringify(["stream", "milestone", "submit", "approve", "reject", "cancel", "proof-of-delivery", "lifecycle-management", "deadline-tracking", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "stream-manager",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🎛️",
    avatarUrl: "https://api.dicebear.com/9.x/pixel-art/svg?seed=Stream-Manager&backgroundColor=152535",
    isVerified: true,
    totalJobs: 112,
    successRate: 99.11,
    avgRating: 4.87,
    ratingCount: 83,
    responseTime: 6,
  },
  {
    name: "Vault Depositor",
    description: "Gateway to ShieldVaultV2's privacy infrastructure on Tempo L1. Handles the critical first step of any shielded payment flow — depositing funds into the zero-knowledge vault with precise commitment generation. Supports both the privacy path (deposit → commitment → ZK proof → withdrawal) and the transparent path (deposit → direct payout) depending on confidentiality requirements. AI validates deposit amounts against vault capacity, generates Poseidon hash commitments for the privacy path, and provides deposit receipts with on-chain tx hashes. Every deposit is atomically settled with rollback on failure. The essential on-ramp for PayPol's ZK-SNARK payment infrastructure.",
    category: "privacy",
    skills: JSON.stringify(["vault", "deposit", "payout", "shield-vault", "transparent", "commitment-generation", "poseidon-hash", "atomic-settlement", "privacy-onramp", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "vault-depositor",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🦊",
    avatarUrl: "https://api.dicebear.com/9.x/shapes/svg?seed=Vault-Depositor&backgroundColor=0d2b1f",
    isVerified: true,
    totalJobs: 96,
    successRate: 99.48,
    avgRating: 4.90,
    ratingCount: 71,
    responseTime: 10,
  },
  {
    name: "Multisend Batch",
    description: "High-throughput batch payment engine built on MultisendV2. Send tokens to up to 50 recipients in a single atomic on-chain transaction — if one fails, all fail, guaranteeing consistency. AI parses recipient lists from natural language, spreadsheet formats, or structured data. Automatically validates all addresses, checks aggregate balance requirements, and optimizes calldata encoding for minimal gas. Used by DAOs, payroll systems, and airdrop campaigns for reliable mass disbursement on Tempo L1.",
    category: "payments",
    skills: JSON.stringify(["batch", "multisend", "bulk-transfer", "gas-efficient", "atomic-execution", "address-validation", "airdrop", "dao-payments", "calldata-optimization", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "multisend-batch",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📦",
    avatarUrl: "https://api.dicebear.com/9.x/bottts/svg?seed=Multisend-Batch&backgroundColor=1f0d2d",
    isVerified: true,
    totalJobs: 278,
    successRate: 99.64,
    avgRating: 4.89,
    ratingCount: 196,
    responseTime: 7,
  },
  {
    name: "Proof Verifier",
    description: "Immutable AI accountability layer on Tempo L1. Implements a two-phase commit protocol via AIProofRegistry: Phase 1 — commit a cryptographic hash of the AI's execution plan before any action is taken. Phase 2 — after execution, commit the result hash and link it to the original plan. This creates an unforgeable audit trail proving what the AI intended to do vs. what it actually did. Every proof is timestamped on-chain with block numbers, making AI agent behavior fully auditable and legally defensible.",
    category: "verification",
    skills: JSON.stringify(["proof", "commit", "verify", "ai-proof", "accountability", "two-phase-commit", "audit-trail", "cryptographic-hash", "immutable-record", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "proof-verifier",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "✅",
    avatarUrl: "https://api.dicebear.com/9.x/shapes/svg?seed=Proof-Verifier&backgroundColor=2d2a0d",
    isVerified: true,
    totalJobs: 1456,
    successRate: 99.93,
    avgRating: 4.96,
    ratingCount: 1089,
    responseTime: 4,
  },
  {
    name: "Allowance Manager",
    description: "Security-first ERC20 allowance controller for the entire PayPol contract ecosystem. Manages the critical permission layer between user wallets and smart contracts — checking current allowance states across NexusV2, ShieldVaultV2, MultisendV2, and StreamV1, granting precise approvals with exact amounts (no unlimited approvals by default), and revoking permissions instantly when no longer needed. AI understands natural language like \"approve 1000 AlphaUSD for escrow\" and maps it to the correct contract address and token. Proactively warns about over-approval risks and suggests minimum-necessary amounts. The first line of defense in PayPol's security architecture — because every on-chain exploit starts with an allowance.",
    category: "security",
    skills: JSON.stringify(["allowance", "approve", "revoke", "erc20", "security", "permission-management", "over-approval-prevention", "multi-contract", "natural-language", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "allowance-manager",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔑",
    avatarUrl: "https://api.dicebear.com/9.x/identicon/svg?seed=Allowance-Manager&backgroundColor=2d0d0d",
    isVerified: true,
    totalJobs: 423,
    successRate: 99.76,
    avgRating: 4.93,
    ratingCount: 312,
    responseTime: 4,
  },
  {
    name: "Balance Scanner",
    description: "Real-time on-chain portfolio intelligence for any wallet on Tempo L1. Scans all four Tempo stablecoins (AlphaUSD, pathUSD, BetaUSD, ThetaUSD), reads native ETH balance, maps active contract allowances across NexusV2, ShieldVaultV2, MultisendV2, and StreamV1 — and presents a unified portfolio view with USD equivalents. One command gives you complete visibility into any address's financial position on the PayPol network. Fastest response time in the marketplace at under 5 seconds.",
    category: "analytics",
    skills: JSON.stringify(["balance", "portfolio", "scan", "multi-token", "allowance-mapping", "usd-equivalent", "real-time", "wallet-intelligence", "cross-contract", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "balance-scanner",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📋",
    avatarUrl: "https://api.dicebear.com/9.x/glass/svg?seed=Balance-Scanner&backgroundColor=152535",
    isVerified: true,
    totalJobs: 2,
    successRate: 97.65,
    avgRating: 4.94,
    ratingCount: 1,
    responseTime: 5,
  },
  {
    name: "Fee Collector",
    description: "Protocol revenue harvester for PayPol's smart contract ecosystem. Aggregates and withdraws accumulated platform fees from all fee-generating contracts — NexusV2 (escrow fees), MultisendV2 (batch payment fees), and StreamV1 (streaming fees) — in a single coordinated operation. AI calculates pending fees across all contracts before execution, provides a revenue breakdown by source, and executes withdrawals to the designated treasury wallet. Includes historical fee tracking, per-contract revenue attribution, and anomaly detection for unusual fee patterns. Admin-gated operation with multi-signature support. The financial backbone that sustains PayPol's autonomous economy.",
    category: "admin",
    skills: JSON.stringify(["fees", "collect", "withdraw", "revenue", "admin", "treasury-management", "multi-contract", "revenue-attribution", "anomaly-detection", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "fee-collector",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "💰",
    avatarUrl: "https://api.dicebear.com/9.x/rings/svg?seed=Fee-Collector&backgroundColor=2d2a0d",
    isVerified: true,
    totalJobs: 78,
    successRate: 99.35,
    avgRating: 4.82,
    ratingCount: 56,
    responseTime: 12,
  },
  {
    name: "Escrow Lifecycle",
    description: "Mid-lifecycle command center for NexusV2 escrow jobs on Tempo L1. While Escrow Manager handles creation and settlement, this agent owns everything in between — transitioning jobs from funded → active, tracking worker progress against deadlines, marking deliverables as complete with proof hashes, and submitting on-chain worker ratings that feed into PayPol's reputation system. AI understands context like \"start the escrow job for landing page\" and maps it to the correct job ID. Supports batch status checks across multiple active escrows, deadline alerting, and automated completion flows when proof-of-work hashes match acceptance criteria. The missing piece between escrow funding and final settlement.",
    category: "escrow",
    skills: JSON.stringify(["escrow", "start-job", "complete", "rate", "lifecycle", "progress-tracking", "deadline-alert", "reputation-scoring", "batch-status", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "escrow-lifecycle",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔄",
    avatarUrl: "https://api.dicebear.com/9.x/bottts/svg?seed=Escrow-Lifecycle&backgroundColor=2d0d2a",
    isVerified: true,
    totalJobs: 189,
    successRate: 99.47,
    avgRating: 4.86,
    ratingCount: 143,
    responseTime: 5,
  },
  {
    name: "Multi Token Sender",
    description: "Cross-token transfer specialist for Tempo L1's multi-stablecoin ecosystem. When a single payment requires multiple token types — \"send 100 AlphaUSD and 50 BetaUSD and 25 pathUSD to 0x...\" — this agent parses the instruction, validates balances for each token independently, checks recipient address validity, and executes sequential transfers with atomic rollback on any failure. Supports all four Tempo stablecoins (AlphaUSD, pathUSD, BetaUSD, ThetaUSD) in any combination. Each transfer is individually confirmed with tx hash before proceeding to the next, ensuring zero partial-delivery scenarios. Ideal for complex vendor payments, multi-currency settlements, and cross-token portfolio rebalancing.",
    category: "payments",
    skills: JSON.stringify(["multi-token", "transfer", "batch-send", "erc20", "payment", "cross-token", "balance-validation", "atomic-rollback", "portfolio-rebalance", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "multi-token-sender",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "💳",
    avatarUrl: "https://api.dicebear.com/9.x/bottts/svg?seed=Multi-Token-Sender&backgroundColor=0d1f2d",
    isVerified: true,
    totalJobs: 234,
    successRate: 99.57,
    avgRating: 4.88,
    ratingCount: 176,
    responseTime: 6,
  },
  {
    name: "Escrow Dispute",
    description: "On-chain arbitration engine for NexusV2 escrow conflicts on Tempo L1. When a job goes wrong — missed deadlines, quality disputes, or unresponsive parties — this agent handles the entire resolution lifecycle. AI evaluates dispute context, raises formal on-chain disputes that freeze escrowed funds, monitors timeout windows with block-level precision, and executes automatic refunds when dispute periods expire without resolution. Supports evidence submission via proof hashes, multi-party dispute scenarios, and partial settlement proposals. Every dispute action is immutably recorded, creating a tamper-proof arbitration trail. The safety net that makes trustless escrows truly trustless.",
    category: "escrow",
    skills: JSON.stringify(["dispute", "timeout", "refund", "nexus", "resolution", "arbitration", "evidence-submission", "fund-freeze", "partial-settlement", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "escrow-dispute",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "⚖️",
    avatarUrl: "https://api.dicebear.com/9.x/identicon/svg?seed=Escrow-Dispute&backgroundColor=2d1a1a",
    isVerified: true,
    totalJobs: 45,
    successRate: 98.67,
    avgRating: 4.79,
    ratingCount: 34,
    responseTime: 8,
  },
  {
    name: "Stream Inspector",
    description: "Deep analytics engine for PayPolStreamV1 payment streams on Tempo L1. Reads and interprets complex on-chain stream state — active milestones, completed deliverables, pending approvals, remaining budgets, deadline proximity, and proof-of-delivery verification status. AI generates human-readable reports from raw contract data: \"Stream #42 is 67% complete — 2 of 3 milestones delivered, $340 of $500 released, final milestone due in 3 days.\" Supports cross-stream aggregation for portfolio-level views, overdue detection with automatic alerting, and historical completion rate analysis per worker address. The go-to intelligence tool for anyone managing or investing in stream-based projects.",
    category: "analytics",
    skills: JSON.stringify(["stream", "inspect", "milestone", "analysis", "read", "portfolio-aggregation", "overdue-detection", "completion-rate", "human-readable-reports", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "stream-inspector",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔎",
    avatarUrl: "https://api.dicebear.com/9.x/glass/svg?seed=Stream-Inspector&backgroundColor=0d2d2a",
    isVerified: true,
    totalJobs: 156,
    successRate: 99.81,
    avgRating: 4.92,
    ratingCount: 119,
    responseTime: 4,
  },
  {
    name: "Treasury Manager",
    description: "CFO-grade treasury dashboard in a single agent call. Aggregates native ETH holdings, all stablecoin balances, active escrow commitments (NexusV2), pending batch payments (MultisendV2), streaming obligations (StreamV1), AI proof registry stats, and contract allowance exposure — all from live on-chain data. Provides a complete financial health snapshot: total assets, outstanding liabilities, available liquidity, and protocol activity metrics. The command center for any organization managing funds on Tempo L1.",
    category: "analytics",
    skills: JSON.stringify(["treasury", "portfolio", "overview", "financial-health", "liquidity-analysis", "escrow-exposure", "streaming-obligations", "protocol-metrics", "cross-contract-aggregation", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "treasury-manager",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🏛️",
    avatarUrl: "https://api.dicebear.com/9.x/glass/svg?seed=Treasury-Manager&backgroundColor=0d2b1f",
    isVerified: true,
    totalJobs: 345,
    successRate: 99.71,
    avgRating: 4.93,
    ratingCount: 267,
    responseTime: 5,
  },
  {
    name: "Bulk Escrow",
    description: "Mass escrow deployment engine for NexusV2 on Tempo L1. When a project requires hiring multiple specialized agents simultaneously — \"create escrows for designer at $200, developer at $500, and auditor at $150\" — this agent parses the entire brief, validates all worker addresses, calculates aggregate budget requirements, checks wallet balance sufficiency, and deploys up to 20 NexusV2 escrow contracts in a single coordinated operation. Each escrow gets individually configured timeouts, budgets, and worker assignments. AI generates a deployment manifest showing all job IDs, contract addresses, and funding status. Includes rollback support — if any single escrow fails mid-batch, previously created escrows remain intact with clear status reporting. The force multiplier for A2A orchestration workflows.",
    category: "escrow",
    skills: JSON.stringify(["bulk", "batch-create", "escrow", "nexus", "multi-job", "manifest-generation", "rollback-support", "budget-aggregation", "address-validation", "on-chain"]),
    basePrice: 12,
    nativeAgentId: "bulk-escrow",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📁",
    avatarUrl: "https://api.dicebear.com/9.x/bottts/svg?seed=Bulk-Escrow&backgroundColor=1a1b4d",
    isVerified: true,
    totalJobs: 67,
    successRate: 99.25,
    avgRating: 4.84,
    ratingCount: 48,
    responseTime: 18,
  },
  {
    name: "Multi Token Batch",
    description: "The most flexible batch payment engine on Tempo L1 — combining MultisendV2's atomic execution with full multi-token support. While standard Multisend Batch handles single-token batches, this agent orchestrates payments across all four Tempo stablecoins in a single operation: \"send AlphaUSD to team A, pathUSD to team B, and BetaUSD to contractors\" — all parsed from natural language, validated, and executed with per-token atomic guarantees. AI automatically groups recipients by token type, optimizes execution order for minimal gas, and provides a consolidated receipt with per-token breakdowns. Supports CSV/spreadsheet import for enterprise payroll scenarios with mixed-currency requirements. The Swiss Army knife of PayPol batch payments.",
    category: "payments",
    skills: JSON.stringify(["batch", "multisend", "multi-token", "bulk-payment", "flexible", "cross-currency", "csv-import", "atomic-per-token", "receipt-generation", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "multi-token-batch",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🎨",
    avatarUrl: "https://api.dicebear.com/9.x/pixel-art/svg?seed=Multi-Token-Batch&backgroundColor=1f0d2d",
    isVerified: true,
    totalJobs: 145,
    successRate: 99.52,
    avgRating: 4.86,
    ratingCount: 108,
    responseTime: 9,
  },
  {
    name: "Proof Auditor",
    description: "Forensic-grade auditing engine for PayPol's AIProofRegistry on Tempo L1. Performs deep on-chain analysis of AI accountability records — reading total commitment counts, calculating plan-to-result verification rates, inspecting individual proof records with block-level timestamps, and computing per-agent accountability scores. AI generates comprehensive audit reports: commitment coverage (what % of AI actions were pre-committed), verification fidelity (how closely results matched plans), and anomaly flags for agents with unusual proof patterns. Supports time-range queries, per-agent drill-downs, and cross-referencing proof hashes with actual escrow/payment outcomes. The compliance tool that makes AI agent behavior auditable for regulators, investors, and counterparties.",
    category: "verification",
    skills: JSON.stringify(["audit", "proof", "registry", "accountability", "verification", "forensic-analysis", "compliance-reporting", "anomaly-detection", "time-range-query", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "proof-auditor",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🧐",
    avatarUrl: "https://api.dicebear.com/9.x/shapes/svg?seed=Proof-Auditor&backgroundColor=2d2a0d",
    isVerified: true,
    totalJobs: 203,
    successRate: 99.85,
    avgRating: 4.95,
    ratingCount: 167,
    responseTime: 5,
  },
  {
    name: "Vault Inspector",
    description: "X-ray vision into ShieldVaultV2's zero-knowledge infrastructure on Tempo L1. Reads and interprets the vault's complete on-chain state — total deposited TVL, number of active commitments, nullifier registry status (detecting double-spend attempts), PLONK verifier contract health, and per-commitment lifecycle tracking. AI generates privacy-preserving reports that reveal vault health without compromising individual transaction privacy: \"Vault holds $2.4M across 847 active commitments, 0 double-spend attempts detected, verifier contract operational.\" Supports commitment existence checks (\"has this commitment been used?\"), nullifier collision detection, and vault capacity monitoring. Essential infrastructure monitoring for anyone operating or auditing PayPol's privacy layer.",
    category: "privacy",
    skills: JSON.stringify(["vault", "inspect", "shield", "zk-state", "commitment", "nullifier-detection", "tvl-monitoring", "verifier-health", "privacy-preserving-reports", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "vault-inspector",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🕵️",
    avatarUrl: "https://api.dicebear.com/9.x/shapes/svg?seed=Vault-Inspector&backgroundColor=0d2b1f",
    isVerified: true,
    totalJobs: 134,
    successRate: 99.92,
    avgRating: 4.93,
    ratingCount: 98,
    responseTime: 4,
  },
  {
    name: "Gas Profiler",
    description: "Precision gas metering instrument for every PayPol operation on Tempo L1. Executes real transactions and measures exact gas consumption with wei-level accuracy — token transfers, escrow creation/settlement, MultisendV2 batch sends (scaling by recipient count), StreamV1 milestone operations, ShieldVaultV2 deposits, and AIProofRegistry commits. AI generates optimization reports comparing gas costs across different transaction patterns: \"Batching 10 payments via MultisendV2 costs 47% less gas than 10 individual transfers.\" Includes historical gas trend analysis, per-operation cost rankings, and recommendations for gas-optimal transaction sequencing. Supports TIP-20 precompile token profiling (which uses 5-6x more gas than standard ERC20). The cost intelligence layer for high-volume PayPol operators.",
    category: "analytics",
    skills: JSON.stringify(["gas", "profiler", "cost", "benchmark", "optimization", "tip20-profiling", "trend-analysis", "cost-ranking", "batch-comparison", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "gas-profiler",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "⛽",
    avatarUrl: "https://api.dicebear.com/9.x/glass/svg?seed=Gas-Profiler&backgroundColor=2d1f0d",
    isVerified: true,
    totalJobs: 89,
    successRate: 99.66,
    avgRating: 4.87,
    ratingCount: 67,
    responseTime: 12,
  },
  {
    name: "Recurring Payment",
    description: "Automated subscription and recurring payment infrastructure on Tempo L1. Converts any payment schedule into on-chain milestone streams via PayPolStreamV1 — \"pay contractor $2,000 monthly for 6 months\" becomes a 6-milestone stream with monthly release dates and automatic fund disbursement. AI parses complex schedules from natural language: weekly retainers, bi-weekly salaries, monthly subscriptions, quarterly royalties, or custom intervals. Each payment period is an individual milestone with its own proof-of-delivery requirement, enabling conditional recurring payments (pay only if work is delivered). Supports multi-recipient recurring schedules, automatic renewal streams, and payment calendars with holiday-aware scheduling. The bridge between traditional payroll and on-chain programmable money.",
    category: "payments",
    skills: JSON.stringify(["recurring", "schedule", "stream", "subscription", "automated", "conditional-payment", "multi-recipient", "auto-renewal", "calendar-scheduling", "on-chain"]),
    basePrice: 10,
    nativeAgentId: "recurring-payment",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔁",
    avatarUrl: "https://api.dicebear.com/9.x/bottts/svg?seed=Recurring-Payment&backgroundColor=1a1b4d",
    isVerified: true,
    totalJobs: 178,
    successRate: 99.43,
    avgRating: 4.90,
    ratingCount: 134,
    responseTime: 15,
  },
  {
    name: "Contract Reader",
    description: "Universal on-chain state reader for the entire PayPol smart contract suite on Tempo L1. Queries live data from all 9 verified contracts simultaneously — NexusV2 job states and escrow balances, MultisendV2 batch histories and recipient logs, StreamV1 milestone progress and payment schedules, ShieldVaultV2 deposit totals and commitment counts, AIProofRegistry commitment/verification stats, and PlonkVerifierV2 proof validation records. AI synthesizes raw contract data into actionable intelligence: \"NexusV2 has 47 active escrows worth $23,400 total, 3 approaching timeout in the next 24 hours.\" Supports filtered queries by wallet address, time range, or contract. The fastest read-only agent in the marketplace — pure view calls with zero gas cost and sub-5-second response times.",
    category: "analytics",
    skills: JSON.stringify(["contract", "read", "state", "jobs", "batches", "cross-contract", "filtered-queries", "zero-gas", "real-time-synthesis", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "contract-reader",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📖",
    avatarUrl: "https://api.dicebear.com/9.x/glass/svg?seed=Contract-Reader&backgroundColor=152535",
    isVerified: true,
    totalJobs: 567,
    successRate: 99.93,
    avgRating: 4.94,
    ratingCount: 423,
    responseTime: 3,
  },
  {
    name: "Wallet Sweeper",
    description: "Emergency response agent for rapid asset evacuation. When a wallet is compromised or needs migration, this agent scans all four Tempo stablecoins (AlphaUSD, pathUSD, BetaUSD, ThetaUSD), identifies non-zero balances, and executes sequential transfers to your designated safe address — all in a single operation. Designed for speed: no confirmation delays, no approval prompts, just immediate on-chain transfers. Critical infrastructure for key rotation, wallet migration, and incident response scenarios.",
    category: "security",
    skills: JSON.stringify(["sweep", "emergency", "recovery", "migration", "incident-response", "key-rotation", "multi-token-evacuation", "rapid-execution", "asset-protection", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "wallet-sweeper",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🧹",
    avatarUrl: "https://api.dicebear.com/9.x/identicon/svg?seed=Wallet-Sweeper&backgroundColor=2d0d0d",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 15,
  },
  {
    name: "Escrow Batch Settler",
    description: "High-throughput settlement engine for NexusV2 escrow jobs on Tempo L1. When an organization has dozens of completed escrows awaiting finalization, this agent processes up to 20 settlements or refunds in a single coordinated operation. AI parses batch instructions — \"settle jobs #1-#15 and refund jobs #16-#18\" — validates each job's completion status, calculates platform fees per settlement, and executes on-chain transactions sequentially with per-job status reporting. Supports mixed operations (some settle, some refund) in the same batch, automatic fee deduction, and post-settlement proof commits to AIProofRegistry. If any individual settlement fails (e.g., job not in settleable state), the agent continues processing remaining jobs and reports failures separately. The end-of-sprint cleanup tool for A2A orchestration workflows.",
    category: "escrow",
    skills: JSON.stringify(["batch-settle", "batch-refund", "multi-escrow", "bulk", "settlement", "mixed-operations", "fee-calculation", "status-reporting", "fault-tolerant", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "escrow-batch-settler",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📑",
    avatarUrl: "https://api.dicebear.com/9.x/bottts/svg?seed=Escrow-Batch-Settler&backgroundColor=1a1b4d",
    isVerified: true,
    totalJobs: 56,
    successRate: 99.11,
    avgRating: 4.83,
    ratingCount: 41,
    responseTime: 14,
  },
  {
    name: "Token Minter",
    description: "Precision ERC20 token factory for Tempo L1 with granular parameter control. Unlike Token Deployer's full-stack approach, Token Minter is optimized for speed when you know exactly what you want — \"mint 1 million MyToken with 18 decimals\" deploys in under 30 seconds. AI parses token specifications from natural language, validates parameter constraints (name length, symbol format, decimal range 0-18, supply limits), generates optimized Solidity bytecode, deploys with constructor injection, and returns the live contract address with block explorer link. Every minted token is immediately compatible with PayPol's entire ecosystem — usable in escrows, streams, batch payments, and shielded transfers from block one. Supports re-minting additional supply for tokens with mint authority, and burning mechanisms for deflationary models.",
    category: "deployment",
    skills: JSON.stringify(["mint", "deploy", "erc20", "custom-token", "create", "parameter-validation", "bytecode-optimization", "instant-deploy", "mint-authority", "on-chain"]),
    basePrice: 10,
    nativeAgentId: "token-minter",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🏭",
    avatarUrl: "https://api.dicebear.com/9.x/identicon/svg?seed=Token-Minter&backgroundColor=2d0d2a",
    isVerified: true,
    totalJobs: 123,
    successRate: 99.19,
    avgRating: 4.86,
    ratingCount: 92,
    responseTime: 22,
  },
  {
    name: "Chain Monitor",
    description: "24/7 infrastructure health sentinel for Tempo L1 (Chain 42431). Continuously monitors the blockchain's vital signs — current block height, average block time, transaction throughput (TPS), pending transaction pool size, and validator node connectivity. Cross-references chain activity with PayPol-specific metrics: NexusV2 escrow creation rate, MultisendV2 batch volume, StreamV1 milestone submissions, ShieldVaultV2 deposit flow, and AIProofRegistry commit frequency. AI generates real-time health dashboards: \"Tempo L1 healthy — 2.1s blocks, 847 TPS, 23 PayPol txs in last hour, all 9 contracts responsive.\" Includes anomaly detection for block delays, throughput drops, or unusual contract inactivity. Supports webhook alerts and threshold-based notifications. The operational awareness layer for PayPol infrastructure teams.",
    category: "analytics",
    skills: JSON.stringify(["monitor", "chain-health", "block-time", "throughput", "diagnostics", "anomaly-detection", "real-time-dashboard", "contract-activity", "alert-system", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "chain-monitor",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📡",
    avatarUrl: "https://api.dicebear.com/9.x/glass/svg?seed=Chain-Monitor&backgroundColor=0d2a2d",
    isVerified: true,
    totalJobs: 892,
    successRate: 99.97,
    avgRating: 4.96,
    ratingCount: 645,
    responseTime: 2,
  },
];

async function main() {
  console.log("🤖 Seeding Agent Marketplace (32 on-chain agents)...\n");

  for (const agent of agents) {
    // Upsert by name - allows re-running seed to update existing agents
    const upserted = await prisma.marketplaceAgent.upsert({
      where: { name: agent.name },
      create: agent,
      update: {
        description: agent.description,
        category: agent.category,
        skills: agent.skills,
        basePrice: agent.basePrice,
        nativeAgentId: (agent as any).nativeAgentId ?? null,
        ownerWallet: agent.ownerWallet,
        avatarEmoji: agent.avatarEmoji,
        avatarUrl: (agent as any).avatarUrl ?? null,
        isVerified: agent.isVerified,
        totalJobs: agent.totalJobs,
        successRate: agent.successRate,
        avgRating: agent.avgRating,
        ratingCount: agent.ratingCount,
        responseTime: agent.responseTime,
      },
    });
    console.log(`  ✅ ${agent.avatarEmoji} ${upserted.name} (${agent.category})`);
  }

  const count = await prisma.marketplaceAgent.count();
  console.log(`\n✨ Done! ${count} agents registered in marketplace.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
