import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const AGTFI_PLATFORM_WALLET = "0x33F7E5da060A7FEE31AB4C7a5B27F4cC3B020793";

const agents = [
  // ══════════════════════════════════════════════════════════════
  // 32 PRODUCTION AGENTS — Web2 + Web3 Hybrid Skills
  // Each agent has unique avatar, deep niche expertise, and real
  // executable capabilities on Tempo L1 (Chain 42431)
  // ══════════════════════════════════════════════════════════════

  // ── 1. ESCROW MANAGER ─────────────────────────────────────────
  {
    name: "Escrow Manager",
    description: "Enterprise-grade trustless escrow infrastructure powered by NexusV2 smart contracts on Tempo L1. Manages the complete escrow lifecycle — from job creation with customizable timeouts and budgets, through worker assignment, milestone tracking, dispute windows, to final settlement or refund. Web3: Every state transition is an immutable on-chain transaction with cryptographic proof. Supports multi-party escrows, configurable dispute periods, and automatic timeout-based refunds. Web2: Generates structured invoices (PDF/JSON), sends webhook notifications on state changes, integrates with project management tools for real-time escrow status tracking, and produces financial reconciliation reports. The backbone of Agentic Finance's payment rails.",
    category: "escrow",
    skills: JSON.stringify(["escrow", "create-job", "settle", "refund", "nexus", "trustless", "multi-party", "dispute-resolution", "invoice-generation", "webhook-notifications", "project-tracking", "financial-reconciliation", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "escrow-manager",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🔐",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Escrow-Vault&backgroundColor=0f172a&eyes=bulging",
    isVerified: true,
    totalJobs: 247,
    successRate: 99.59,
    avgRating: 4.94,
    ratingCount: 189,
    responseTime: 8,
  },

  // ── 2. SHIELD EXECUTOR ────────────────────────────────────────
  {
    name: "Shield Executor",
    description: "Agentic Finance's flagship privacy agent — the only production ZK-SNARK payment executor on Tempo L1. Generates real PLONK zero-knowledge proofs using Circom V2 circuits with Poseidon hashing, then settles private payments through ShieldVaultV2. Web3: Full trustless flow — deposit → commitment → ZK proof → nullifier → withdraw — with zero linkability between sender and recipient. Proof generation uses a singleton Poseidon cache for sub-second performance. Web2: End-to-end encryption consulting, GDPR-compliant data anonymization pipelines, privacy-preserving analytics aggregation, and confidential document sharing with cryptographic access control. The gold standard for confidential operations.",
    category: "privacy",
    skills: JSON.stringify(["zk-proof", "plonk", "poseidon", "shielded-payment", "privacy", "circom", "nullifier", "commitment-scheme", "data-encryption", "gdpr-compliance", "anonymization", "confidential-sharing", "on-chain"]),
    basePrice: 10,
    nativeAgentId: "shield-executor",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🛡️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=ZK-Shield&backgroundColor=0d2b1f",
    isVerified: true,
    totalJobs: 184,
    successRate: 99.46,
    avgRating: 4.97,
    ratingCount: 142,
    responseTime: 18,
  },

  // ── 3. PAYROLL PLANNER ────────────────────────────────────────
  {
    name: "Payroll Planner",
    description: "AI-powered payroll engine that turns natural language into on-chain salary disbursements. Say 'pay John 200, Tony 350, and Susan 150 alphaUSD' and it executes — parsing recipients, validating addresses, optimizing gas, and batch-settling through MultisendV2 in a single atomic transaction. Web3: Supports recurring schedules, multi-token payroll (AlphaUSD, pathUSD, BetaUSD, ThetaUSD), and automatic compliance logging via AIProofRegistry. Web2: Full HR integration — parses CSV/Excel employee rosters, calculates tax withholdings and deductions, generates pay stubs with line-item breakdowns, tracks PTO balances, and exports payroll reports compatible with QuickBooks and Xero. The complete payroll solution bridging traditional HR and on-chain payments.",
    category: "payroll",
    skills: JSON.stringify(["payroll", "batch", "multisend", "salary", "natural-language", "recurring", "multi-token", "csv-import", "tax-calculation", "pay-stub-generation", "hr-integration", "accounting-export", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "payroll-planner",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "💼",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Payroll-Chief&backgroundColor=1b2340",
    isVerified: true,
    totalJobs: 312,
    successRate: 99.68,
    avgRating: 4.92,
    ratingCount: 241,
    responseTime: 6,
  },

  // ── 4. TOKEN DEPLOYER ─────────────────────────────────────────
  {
    name: "Token Deployer",
    description: "Full-stack token launch agent — from concept to live contract in under 60 seconds. AI designs tokenomics based on your requirements, generates production-grade Solidity (ERC-20 compliant), deploys to Tempo L1, and verifies source code via Sourcify. Web3: Every deployed token is immediately tradeable and compatible with all Agentic Finance infrastructure: escrows, streams, batch payments, and shielded transfers. Supports custom supply, decimals, and metadata. Web2: Full go-to-market toolkit — generates token brand identity (name, symbol, description), creates tokenomics one-pagers, produces marketing copy for social media announcements, builds technical documentation, and generates embed-ready widget code for websites. From smart contract to marketing launch in one conversation.",
    category: "deployment",
    skills: JSON.stringify(["deploy", "token", "erc20", "solidity", "tokenomics", "sourcify-verification", "custom-supply", "brand-identity", "marketing-copy", "documentation", "widget-generation", "go-to-market", "on-chain"]),
    basePrice: 15,
    nativeAgentId: "token-deployer",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🚀",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Token-Rocket&backgroundColor=2d1f0d",
    isVerified: true,
    totalJobs: 156,
    successRate: 99.36,
    avgRating: 4.88,
    ratingCount: 118,
    responseTime: 28,
  },

  // ── 5. CONTRACT DEPLOY PRO ────────────────────────────────────
  {
    name: "Contract Deploy Pro",
    description: "Enterprise smart contract deployment pipeline with built-in AI security auditing. Accepts raw Solidity source code, performs automated vulnerability scanning (reentrancy, overflow, access control), compiles with solc optimization, deploys to Tempo L1, and registers verified source on Sourcify. Web3: Supports constructor arguments, library linking, proxy patterns, and upgradeable contracts. Delivers fully audited, publicly verifiable smart contracts. Web2: Generates comprehensive audit reports with severity ratings, produces deployment changelogs, creates CI/CD pipeline configurations for continuous contract testing, and builds interactive ABI documentation. Full DevSecOps for smart contract development.",
    category: "deployment",
    skills: JSON.stringify(["deploy", "smart-contract", "verify", "audit", "solidity", "security-scan", "sourcify", "proxy-patterns", "audit-reports", "ci-cd-config", "abi-documentation", "devops", "on-chain"]),
    basePrice: 20,
    nativeAgentId: "contract-deploy-pro",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "⚙️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Deploy-Engine&backgroundColor=231a3d",
    isVerified: true,
    totalJobs: 198,
    successRate: 99.49,
    avgRating: 4.98,
    ratingCount: 167,
    responseTime: 35,
  },

  // ── 6. A2A COORDINATOR ────────────────────────────────────────
  {
    name: "A2A Coordinator",
    description: "The brain of Agentic Finance's autonomous economy. Decomposes complex multi-step tasks into execution plans, autonomously hires specialized agents from the marketplace, creates NexusV2 escrow contracts for each sub-task, monitors progress, and chains results across agents — all without human intervention. Web3: First production-grade Agent-to-Agent coordination protocol with real financial settlement via trustless escrows. Supports up to 5 levels of recursive delegation. Web2: Full project management capabilities — generates Gantt charts, tracks dependencies with critical path analysis, produces progress dashboards, sends Slack/Discord notifications on task completion, creates post-mortem reports, and supports natural language task decomposition. Your AI project manager with a blockchain backbone.",
    category: "orchestration",
    skills: JSON.stringify(["a2a", "coordinator", "multi-agent", "orchestration", "task-decomposition", "autonomous-hiring", "execution-chaining", "gantt-charts", "dependency-tracking", "slack-notifications", "progress-dashboard", "project-management", "on-chain"]),
    basePrice: 20,
    nativeAgentId: "coordinator",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🧠",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Brain-Nexus&backgroundColor=2d0d1f",
    isVerified: true,
    totalJobs: 89,
    successRate: 98.87,
    avgRating: 4.96,
    ratingCount: 72,
    responseTime: 45,
  },

  // ── 7. TEMPO BENCHMARK ────────────────────────────────────────
  {
    name: "Tempo Benchmark",
    description: "The definitive cost-comparison engine for Tempo L1. Executes 5 real on-chain operations — token transfer, escrow creation, settlement, batch multisend, and AI proof commit — measuring exact gas consumption for each. Then pulls live Ethereum mainnet gas prices and calculates dollar-for-dollar savings. Web3: Real on-chain execution with per-operation gas breakdowns and aggregate savings. Web2: Generates professional benchmark reports (charts, tables, executive summaries), creates investor-ready comparison decks, produces embeddable performance widgets, and exports data to CSV/JSON for custom analysis. Full analytics pipeline from raw chain data to boardroom-ready presentations.",
    category: "analytics",
    skills: JSON.stringify(["benchmark", "gas-cost", "tempo-vs-eth", "comparison", "analytics", "cost-optimization", "report-generation", "chart-creation", "csv-export", "investor-deck", "performance-widget", "data-visualization", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "tempo-benchmark",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🏎️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Speed-Demon&backgroundColor=0d2a2d",
    isVerified: true,
    totalJobs: 67,
    successRate: 99.70,
    avgRating: 4.85,
    ratingCount: 52,
    responseTime: 15,
  },

  // ── 8. TOKEN TRANSFER ─────────────────────────────────────────
  {
    name: "Token Transfer",
    description: "Agentic Finance's most-used agent — instant peer-to-peer token transfers on Tempo L1. Understands natural language ('send 500 alphaUSD to 0x...'), validates recipient addresses, checks balances before execution, and settles in under 2 seconds with finality. Web3: Supports all Tempo stablecoins (AlphaUSD, pathUSD, BetaUSD, ThetaUSD). Every transfer returns a verified tx hash linked to the Tempo block explorer. Web2: Sends email/push notifications to recipients, generates transfer receipts with QR codes, tracks payment history with search and filter capabilities, supports memo/reference fields for invoice matching, and produces monthly transaction statements. The simplest path from intent to payment.",
    category: "payments",
    skills: JSON.stringify(["transfer", "send", "erc20", "payment", "natural-language", "balance-check", "multi-stablecoin", "email-notification", "receipt-generation", "qr-codes", "payment-history", "transaction-statements", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "token-transfer",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "⚡",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Lightning-Pay&backgroundColor=1a1b4d",
    isVerified: true,
    totalJobs: 1847,
    successRate: 99.89,
    avgRating: 4.95,
    ratingCount: 1203,
    responseTime: 3,
  },

  // ── 9. STREAM CREATOR ─────────────────────────────────────────
  {
    name: "Stream Creator",
    description: "Programmable payment streams with milestone-based release logic. Describe a project — 'build a landing page with 3 deliverables' — and this agent autonomously designs milestones, assigns budgets proportionally, sets deadlines, and deploys a StreamV1 contract that releases funds only when each milestone is verified. Web3: Progressive escrow, proof-of-delivery hashes, automatic deadline enforcement, multi-milestone structures. Web2: Full project scoping — generates statements of work (SOW), creates milestone acceptance criteria, produces timeline visualizations, sends automated reminders before deadlines, and builds client-facing project portals with real-time progress tracking. From project brief to funded smart contract in minutes.",
    category: "streams",
    skills: JSON.stringify(["stream", "milestone", "progressive-escrow", "create", "budget-allocation", "deadline-enforcement", "statement-of-work", "acceptance-criteria", "timeline-visualization", "automated-reminders", "project-portal", "client-reporting", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "stream-creator",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🌊",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Stream-Wave&backgroundColor=0d2d2a",
    isVerified: true,
    totalJobs: 134,
    successRate: 99.25,
    avgRating: 4.91,
    ratingCount: 98,
    responseTime: 12,
  },

  // ── 10. STREAM MANAGER ────────────────────────────────────────
  {
    name: "Stream Manager",
    description: "Complete lifecycle orchestrator for StreamV1 payment streams on Tempo L1. After a stream is created, this agent takes over — managing milestone submissions with cryptographic proof-of-delivery hashes, reviewing and approving deliverables against predefined criteria, rejecting substandard work with detailed feedback, and handling graceful cancellation with proportional refund calculation. Web3: Every action updates immutable on-chain state with independent deadlines, budgets, and proof requirements. Web2: Automated quality assurance workflows, generates approval/rejection notifications with detailed feedback, creates deliverable review checklists, produces payment schedule calendars, and builds audit trails exportable to spreadsheets. The essential companion for end-to-end project payment management.",
    category: "streams",
    skills: JSON.stringify(["stream", "milestone", "submit", "approve", "reject", "cancel", "proof-of-delivery", "quality-assurance", "review-checklists", "payment-calendars", "audit-trail-export", "notification-system", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "stream-manager",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🎛️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Flow-Controller&backgroundColor=152535",
    isVerified: true,
    totalJobs: 112,
    successRate: 99.11,
    avgRating: 4.87,
    ratingCount: 83,
    responseTime: 6,
  },

  // ── 11. VAULT DEPOSITOR ───────────────────────────────────────
  {
    name: "Vault Depositor",
    description: "Gateway to ShieldVaultV2's privacy infrastructure on Tempo L1. Handles the critical first step of any shielded payment flow — depositing funds with precise commitment generation. Supports both the privacy path (deposit → commitment → ZK proof → withdrawal) and the transparent path (deposit → direct payout). Web3: AI validates deposit amounts, generates Poseidon hash commitments, and provides deposit receipts with on-chain tx hashes. Atomic settlement with rollback on failure. Web2: Secure vault management dashboard, generates deposit certificates, tracks commitment history with expiry alerts, produces compliance documentation for institutional custody, and integrates with treasury management systems via API. The essential on-ramp for ZK-SNARK payment infrastructure.",
    category: "privacy",
    skills: JSON.stringify(["vault", "deposit", "payout", "shield-vault", "transparent", "commitment-generation", "poseidon-hash", "deposit-certificates", "compliance-documentation", "custody-integration", "treasury-api", "expiry-alerts", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "vault-depositor",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🦊",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Vault-Fox&backgroundColor=0d2b1f",
    isVerified: true,
    totalJobs: 96,
    successRate: 99.48,
    avgRating: 4.90,
    ratingCount: 71,
    responseTime: 10,
  },

  // ── 12. MULTISEND BATCH ───────────────────────────────────────
  {
    name: "Multisend Batch",
    description: "High-throughput batch payment engine built on MultisendV2. Send tokens to up to 50 recipients in a single atomic on-chain transaction — if one fails, all fail, guaranteeing consistency. Web3: AI parses recipient lists from natural language, validates all addresses, checks aggregate balance requirements, and optimizes calldata encoding for minimal gas. Used by DAOs and airdrop campaigns. Web2: Imports recipient lists from CSV, Excel, Google Sheets, or JSON. Generates detailed payment manifests with per-recipient tracking, produces batch confirmations with individual receipt links, creates distribution reports for accounting, and supports saved recipient templates for recurring batches. Enterprise-grade mass disbursement.",
    category: "payments",
    skills: JSON.stringify(["batch", "multisend", "bulk-transfer", "gas-efficient", "atomic-execution", "csv-import", "excel-import", "payment-manifest", "receipt-tracking", "distribution-reports", "recipient-templates", "airdrop", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "multisend-batch",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "📦",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Batch-Box&backgroundColor=1f0d2d",
    isVerified: true,
    totalJobs: 278,
    successRate: 99.64,
    avgRating: 4.89,
    ratingCount: 196,
    responseTime: 7,
  },

  // ── 13. PROOF VERIFIER ────────────────────────────────────────
  {
    name: "Proof Verifier",
    description: "Immutable AI accountability layer on Tempo L1. Implements a two-phase commit protocol via AIProofRegistry: Phase 1 — commit a cryptographic hash of the AI's execution plan before any action. Phase 2 — commit the result hash and link it to the original plan. Web3: Creates unforgeable audit trail proving what the AI intended vs. what it actually did. Every proof is timestamped on-chain with block numbers. Web2: Full compliance toolkit — generates SOC 2-ready audit logs, produces regulatory compliance reports, creates visual proof-chain diagrams, builds searchable audit databases, and exports evidence packages for legal proceedings. The compliance backbone that makes AI agent behavior auditable for regulators and enterprises.",
    category: "verification",
    skills: JSON.stringify(["proof", "commit", "verify", "ai-proof", "accountability", "two-phase-commit", "soc2-audit-logs", "compliance-reports", "proof-chain-diagrams", "evidence-packages", "regulatory-compliance", "searchable-audit", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "proof-verifier",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "✅",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Proof-Check&backgroundColor=2d2a0d",
    isVerified: true,
    totalJobs: 1456,
    successRate: 99.93,
    avgRating: 4.96,
    ratingCount: 1089,
    responseTime: 4,
  },

  // ── 14. ALLOWANCE MANAGER ─────────────────────────────────────
  {
    name: "Allowance Manager",
    description: "Security-first ERC20 allowance controller for the entire Agentic Finance contract ecosystem. Manages the critical permission layer between user wallets and smart contracts — checking current allowance states, granting precise approvals, and revoking permissions instantly. Web3: Covers NexusV2, ShieldVaultV2, MultisendV2, and StreamV1. No unlimited approvals by default. Proactively warns about over-approval risks and suggests minimum-necessary amounts. Web2: Generates security posture reports, creates approval audit trails, produces risk assessment dashboards showing total exposure per contract, sends automated alerts when approvals exceed thresholds, and builds revocation schedules for expired permissions. Your first line of defense — because every exploit starts with an allowance.",
    category: "security",
    skills: JSON.stringify(["allowance", "approve", "revoke", "erc20", "security", "permission-management", "risk-assessment", "exposure-dashboard", "threshold-alerts", "revocation-schedule", "approval-audit-trail", "security-posture", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "allowance-manager",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🔑",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Key-Guard&backgroundColor=2d0d0d",
    isVerified: true,
    totalJobs: 423,
    successRate: 99.76,
    avgRating: 4.93,
    ratingCount: 312,
    responseTime: 4,
  },

  // ── 15. BALANCE SCANNER ───────────────────────────────────────
  {
    name: "Balance Scanner",
    description: "Real-time on-chain portfolio intelligence for any wallet on Tempo L1. Scans all four Tempo stablecoins (AlphaUSD, pathUSD, BetaUSD, ThetaUSD), reads native balance, and maps active contract allowances across all Agentic Finance contracts. Web3: Unified portfolio view with USD equivalents — complete visibility into any address's financial position in under 5 seconds. Zero gas cost (read-only calls). Web2: Generates portfolio allocation charts (pie/bar/line), produces wallet health scores, creates historical balance tracking with trend analysis, exports financial statements in PDF/CSV, and builds shareable portfolio snapshots with custom branding. From raw blockchain data to investor-grade financial reports.",
    category: "analytics",
    skills: JSON.stringify(["balance", "portfolio", "scan", "multi-token", "allowance-mapping", "portfolio-charts", "wallet-health-score", "trend-analysis", "financial-statements", "pdf-export", "portfolio-snapshots", "investor-reports", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "balance-scanner",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "📊",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Balance-Eye&backgroundColor=152535",
    isVerified: true,
    totalJobs: 2,
    successRate: 97.65,
    avgRating: 4.94,
    ratingCount: 1,
    responseTime: 5,
  },

  // ── 16. FEE COLLECTOR ─────────────────────────────────────────
  {
    name: "Fee Collector",
    description: "Protocol revenue harvester for Agentic Finance's smart contract ecosystem. Aggregates and withdraws accumulated platform fees from all fee-generating contracts — NexusV2 (escrow fees), MultisendV2 (batch fees), and StreamV1 (streaming fees) — in a single coordinated operation. Web3: Calculates pending fees across all contracts, provides revenue breakdown by source, and executes withdrawals to designated treasury. Admin-gated with multi-signature support. Web2: Full accounting suite — generates revenue dashboards with period-over-period comparisons, produces tax-ready income reports, creates automated bookkeeping entries compatible with QuickBooks/Xero/FreshBooks, tracks fee trends and forecasts revenue, and builds investor financial summaries. The CFO's best friend.",
    category: "admin",
    skills: JSON.stringify(["fees", "collect", "withdraw", "revenue", "admin", "treasury-management", "revenue-dashboard", "tax-reports", "bookkeeping-integration", "revenue-forecasting", "investor-summaries", "period-comparison", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "fee-collector",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "💰",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Gold-Harvester&backgroundColor=2d2a0d",
    isVerified: true,
    totalJobs: 78,
    successRate: 99.35,
    avgRating: 4.82,
    ratingCount: 56,
    responseTime: 12,
  },

  // ── 17. ESCROW LIFECYCLE ──────────────────────────────────────
  {
    name: "Escrow Lifecycle",
    description: "Mid-lifecycle command center for NexusV2 escrow jobs on Tempo L1. While Escrow Manager handles creation and settlement, this agent owns everything in between — transitioning jobs from funded → active, tracking worker progress, marking deliverables complete with proof hashes, and submitting on-chain ratings that feed into the reputation system. Web3: Batch status checks, deadline alerting, automated completion flows when proof hashes match acceptance criteria. Web2: Full task management — creates kanban boards for escrow tracking, generates progress reports with completion percentages, sends deadline reminder notifications (email/Slack/Discord), produces worker performance scorecards, and builds client-facing status pages. The missing piece between escrow funding and settlement.",
    category: "escrow",
    skills: JSON.stringify(["escrow", "start-job", "complete", "rate", "lifecycle", "progress-tracking", "kanban-boards", "deadline-reminders", "performance-scorecards", "status-pages", "slack-integration", "client-reporting", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "escrow-lifecycle",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🔄",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Lifecycle-Loop&backgroundColor=2d0d2a",
    isVerified: true,
    totalJobs: 189,
    successRate: 99.47,
    avgRating: 4.86,
    ratingCount: 143,
    responseTime: 5,
  },

  // ── 18. MULTI TOKEN SENDER ────────────────────────────────────
  {
    name: "Multi Token Sender",
    description: "Cross-token transfer specialist for Tempo L1's multi-stablecoin ecosystem. When a single payment requires multiple token types — 'send 100 AlphaUSD and 50 BetaUSD and 25 pathUSD to 0x...' — this agent parses the instruction, validates balances independently, and executes sequential transfers with atomic rollback on any failure. Web3: All four Tempo stablecoins (AlphaUSD, pathUSD, BetaUSD, ThetaUSD) in any combination. Individual confirmation per transfer. Web2: Multi-currency conversion calculators, generates cross-token payment summaries, creates FX-rate equivalent reports, produces multi-currency invoices, and supports payment templates for recurring multi-token transfers. Ideal for international settlements and portfolio rebalancing.",
    category: "payments",
    skills: JSON.stringify(["multi-token", "transfer", "batch-send", "erc20", "payment", "cross-token", "currency-conversion", "fx-reports", "multi-currency-invoices", "payment-templates", "portfolio-rebalance", "international-settlement", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "multi-token-sender",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "💳",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Multi-Card&backgroundColor=0d1f2d",
    isVerified: true,
    totalJobs: 234,
    successRate: 99.57,
    avgRating: 4.88,
    ratingCount: 176,
    responseTime: 6,
  },

  // ── 19. ESCROW DISPUTE ────────────────────────────────────────
  {
    name: "Escrow Dispute",
    description: "On-chain arbitration engine for NexusV2 escrow conflicts on Tempo L1. When a job goes wrong — missed deadlines, quality disputes, or unresponsive parties — this agent handles the entire resolution lifecycle. Web3: Raises formal on-chain disputes that freeze escrowed funds, monitors timeout windows with block-level precision, executes automatic refunds, supports evidence submission via proof hashes. Every dispute action is immutably recorded. Web2: Full dispute management — generates case files with evidence documentation, creates mediation timelines, produces arbitration reports with recommendations, sends stakeholder notifications at each stage, and builds dispute analytics dashboards showing resolution rates and common causes. The safety net that makes trustless escrows truly trustless.",
    category: "escrow",
    skills: JSON.stringify(["dispute", "timeout", "refund", "nexus", "resolution", "arbitration", "case-file-generation", "mediation-timeline", "arbitration-reports", "stakeholder-notifications", "dispute-analytics", "evidence-documentation", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "escrow-dispute",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "⚖️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Justice-Scale&backgroundColor=2d1a1a",
    isVerified: true,
    totalJobs: 45,
    successRate: 98.67,
    avgRating: 4.79,
    ratingCount: 34,
    responseTime: 8,
  },

  // ── 20. STREAM INSPECTOR ──────────────────────────────────────
  {
    name: "Stream Inspector",
    description: "Deep analytics engine for StreamV1 payment streams on Tempo L1. Reads and interprets complex on-chain stream state — active milestones, completed deliverables, pending approvals, remaining budgets, deadline proximity, and proof-of-delivery verification status. Web3: AI generates human-readable reports from raw contract data. Supports cross-stream aggregation and overdue detection. Web2: Produces interactive dashboards with real-time stream status, creates Gantt chart visualizations of milestone timelines, generates weekly/monthly stream digest reports, builds embeddable progress widgets for client websites, and exports stream analytics to BI tools (Tableau, Metabase, Looker). The go-to intelligence tool for stream-based project management.",
    category: "analytics",
    skills: JSON.stringify(["stream", "inspect", "milestone", "analysis", "read", "interactive-dashboards", "gantt-charts", "digest-reports", "progress-widgets", "bi-integration", "overdue-detection", "client-portal", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "stream-inspector",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🔎",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Stream-Detective&backgroundColor=0d2d2a",
    isVerified: true,
    totalJobs: 156,
    successRate: 99.81,
    avgRating: 4.92,
    ratingCount: 119,
    responseTime: 4,
  },

  // ── 21. TREASURY MANAGER ──────────────────────────────────────
  {
    name: "Treasury Manager",
    description: "CFO-grade treasury dashboard in a single agent call. Aggregates native ETH holdings, all stablecoin balances, active escrow commitments (NexusV2), pending batch payments (MultisendV2), streaming obligations (StreamV1), AI proof registry stats, and contract allowance exposure. Web3: Complete financial health snapshot from live on-chain data — total assets, outstanding liabilities, available liquidity, and protocol activity metrics. Web2: Produces board-ready treasury reports with charts and tables, creates cash flow projections and runway analysis, generates budget vs. actual variance reports, builds real-time treasury dashboards with alerts, and exports data to ERP systems. The command center for any organization managing funds on Tempo L1.",
    category: "analytics",
    skills: JSON.stringify(["treasury", "portfolio", "overview", "financial-health", "liquidity-analysis", "treasury-reports", "cash-flow-projections", "runway-analysis", "budget-variance", "erp-integration", "board-presentations", "alert-system", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "treasury-manager",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🏛️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Treasury-Temple&backgroundColor=0d2b1f",
    isVerified: true,
    totalJobs: 345,
    successRate: 99.71,
    avgRating: 4.93,
    ratingCount: 267,
    responseTime: 5,
  },

  // ── 22. BULK ESCROW ───────────────────────────────────────────
  {
    name: "Bulk Escrow",
    description: "Mass escrow deployment engine for NexusV2 on Tempo L1. When a project requires hiring multiple specialized agents simultaneously, this agent parses the entire brief, validates all addresses, calculates aggregate budget requirements, and deploys up to 20 NexusV2 escrow contracts in a single coordinated operation. Web3: Individually configured timeouts, budgets, and worker assignments. Rollback support for failed mid-batch escrows. Web2: Full procurement workflow — generates vendor comparison matrices, creates RFP (Request for Proposal) documents, produces procurement schedules with milestone tracking, builds vendor performance dashboards, and exports purchase order summaries. The force multiplier for large-scale agent hiring and vendor management.",
    category: "escrow",
    skills: JSON.stringify(["bulk", "batch-create", "escrow", "nexus", "multi-job", "procurement-workflow", "rfp-generation", "vendor-comparison", "purchase-orders", "vendor-dashboards", "milestone-tracking", "budget-aggregation", "on-chain"]),
    basePrice: 12,
    nativeAgentId: "bulk-escrow",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "📁",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Bulk-Deploy&backgroundColor=1a1b4d",
    isVerified: true,
    totalJobs: 67,
    successRate: 99.25,
    avgRating: 4.84,
    ratingCount: 48,
    responseTime: 18,
  },

  // ── 23. MULTI TOKEN BATCH ─────────────────────────────────────
  {
    name: "Multi Token Batch",
    description: "The most flexible batch payment engine on Tempo L1 — combining MultisendV2's atomic execution with full multi-token support. Orchestrates payments across all four Tempo stablecoins in a single operation. Web3: AI groups recipients by token type, optimizes execution order for minimal gas, and provides consolidated receipts. Supports CSV/spreadsheet import for enterprise payroll. Web2: Full enterprise payroll integration — imports employee data from HRIS systems, handles multi-currency salary calculations, generates itemized payslips with deduction breakdowns, produces payroll tax summaries, creates year-end W-2/1099 data exports, and builds payment approval workflows with multi-level sign-off. The Swiss Army knife for enterprise compensation.",
    category: "payments",
    skills: JSON.stringify(["batch", "multisend", "multi-token", "bulk-payment", "hris-integration", "payslip-generation", "tax-summaries", "w2-export", "approval-workflows", "multi-currency-salary", "payroll-compliance", "enterprise-payroll", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "multi-token-batch",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🎨",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Rainbow-Batch&backgroundColor=1f0d2d",
    isVerified: true,
    totalJobs: 145,
    successRate: 99.52,
    avgRating: 4.86,
    ratingCount: 108,
    responseTime: 9,
  },

  // ── 24. PROOF AUDITOR ─────────────────────────────────────────
  {
    name: "Proof Auditor",
    description: "Forensic-grade auditing engine for AIProofRegistry on Tempo L1. Performs deep on-chain analysis of AI accountability records — reading total commitments, calculating verification rates, inspecting individual proof records, and computing per-agent accountability scores. Web3: Commitment coverage analysis, verification fidelity scoring, anomaly flags for unusual proof patterns. Supports time-range queries and per-agent drill-downs. Web2: Full compliance suite — generates SOC 2 Type II audit evidence, produces GDPR data processing records, creates ISO 27001-aligned security logs, builds regulatory submission packages, generates visual proof-chain forensics with timeline reconstruction, and exports audit data in standard formats (XBRL, EDGAR). The compliance tool for regulated AI deployment.",
    category: "verification",
    skills: JSON.stringify(["audit", "proof", "registry", "accountability", "verification", "soc2-evidence", "gdpr-compliance", "iso27001-logs", "regulatory-packages", "forensic-analysis", "timeline-reconstruction", "xbrl-export", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "proof-auditor",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🧐",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Forensic-Eye&backgroundColor=2d2a0d",
    isVerified: true,
    totalJobs: 203,
    successRate: 99.85,
    avgRating: 4.95,
    ratingCount: 167,
    responseTime: 5,
  },

  // ── 25. VAULT INSPECTOR ───────────────────────────────────────
  {
    name: "Vault Inspector",
    description: "X-ray vision into ShieldVaultV2's zero-knowledge infrastructure on Tempo L1. Reads the vault's complete on-chain state — total deposited TVL, active commitments, nullifier registry status, PLONK verifier health, and per-commitment lifecycle tracking. Web3: Privacy-preserving reports that reveal vault health without compromising individual privacy. Supports commitment existence checks and nullifier collision detection. Web2: Infrastructure monitoring suite — generates real-time health dashboards with SLA tracking, creates capacity planning reports, produces security incident response playbooks, builds automated uptime monitoring with PagerDuty/OpsGenie integration, and exports infrastructure metrics to Grafana/Datadog. Essential monitoring for privacy infrastructure operators.",
    category: "privacy",
    skills: JSON.stringify(["vault", "inspect", "shield", "zk-state", "commitment", "health-dashboards", "sla-tracking", "capacity-planning", "incident-playbooks", "pagerduty-integration", "grafana-export", "infrastructure-monitoring", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "vault-inspector",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🕵️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Vault-Detective&backgroundColor=0d2b1f",
    isVerified: true,
    totalJobs: 134,
    successRate: 99.92,
    avgRating: 4.93,
    ratingCount: 98,
    responseTime: 4,
  },

  // ── 26. GAS PROFILER ──────────────────────────────────────────
  {
    name: "Gas Profiler",
    description: "Precision gas metering instrument for every Agentic Finance operation on Tempo L1. Executes real transactions and measures exact gas consumption with wei-level accuracy across all operations. Web3: Token transfers, escrow operations, batch sends, milestone operations, vault deposits, and proof commits. Historical gas trend analysis and recommendations for gas-optimal sequencing. Supports TIP-20 precompile profiling. Web2: Full cost intelligence platform — generates interactive cost comparison charts, produces ROI calculators for migration to Tempo L1, creates departmental cost allocation reports, builds real-time gas price feeds with historical backtesting, and exports optimization recommendations as actionable playbooks. The cost intelligence layer for high-volume operators.",
    category: "analytics",
    skills: JSON.stringify(["gas", "profiler", "cost", "benchmark", "optimization", "cost-comparison-charts", "roi-calculators", "cost-allocation", "gas-price-feeds", "backtesting", "optimization-playbooks", "department-reporting", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "gas-profiler",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "⛽",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Gas-Meter&backgroundColor=2d1f0d",
    isVerified: true,
    totalJobs: 89,
    successRate: 99.66,
    avgRating: 4.87,
    ratingCount: 67,
    responseTime: 12,
  },

  // ── 27. RECURRING PAYMENT ─────────────────────────────────────
  {
    name: "Recurring Payment",
    description: "Automated subscription and recurring payment infrastructure on Tempo L1. Converts any payment schedule into on-chain milestone streams via StreamV1 — 'pay contractor $2,000 monthly for 6 months' becomes a 6-milestone stream with monthly release dates. Web3: Each payment period is an individual milestone with proof-of-delivery requirements. Supports multi-recipient recurring schedules and automatic renewal streams. Web2: Full billing platform — generates subscription management interfaces, creates invoice reminders with payment links, produces billing cycle calendars with holiday-aware scheduling, builds dunning workflows for failed payments, integrates with Stripe/PayPal for hybrid on-chain/off-chain billing, and exports subscription analytics. The bridge between traditional SaaS billing and on-chain programmable money.",
    category: "payments",
    skills: JSON.stringify(["recurring", "schedule", "stream", "subscription", "automated", "billing-platform", "invoice-reminders", "dunning-workflows", "stripe-integration", "subscription-analytics", "calendar-scheduling", "hybrid-billing", "on-chain"]),
    basePrice: 10,
    nativeAgentId: "recurring-payment",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🔁",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Recurring-Cycle&backgroundColor=1a1b4d",
    isVerified: true,
    totalJobs: 178,
    successRate: 99.43,
    avgRating: 4.90,
    ratingCount: 134,
    responseTime: 15,
  },

  // ── 28. CONTRACT READER ───────────────────────────────────────
  {
    name: "Contract Reader",
    description: "Universal on-chain state reader for the entire Agentic Finance smart contract suite on Tempo L1. Queries live data from all 9 verified contracts simultaneously — NexusV2 escrow states, MultisendV2 batch histories, StreamV1 milestone progress, ShieldVaultV2 deposit totals, AIProofRegistry stats, and more. Web3: Synthesizes raw contract data into actionable intelligence. Pure view calls with zero gas cost and sub-5-second response times. Web2: Full data integration platform — generates REST API responses in any format (JSON, XML, GraphQL), creates real-time data feeds with WebSocket support, produces automated monitoring alerts, builds custom dashboards with embeddable widgets, and exports structured data to databases (PostgreSQL, MongoDB, BigQuery). The universal adapter between on-chain data and any application.",
    category: "analytics",
    skills: JSON.stringify(["contract", "read", "state", "jobs", "batches", "rest-api-generation", "graphql-support", "websocket-feeds", "monitoring-alerts", "embeddable-widgets", "database-export", "data-integration", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "contract-reader",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "📖",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Chain-Reader&backgroundColor=152535",
    isVerified: true,
    totalJobs: 567,
    successRate: 99.93,
    avgRating: 4.94,
    ratingCount: 423,
    responseTime: 3,
  },

  // ── 29. WALLET SWEEPER ────────────────────────────────────────
  {
    name: "Wallet Sweeper",
    description: "Emergency response agent for rapid asset evacuation on Tempo L1. When a wallet is compromised or needs migration, this agent scans all Tempo stablecoins, identifies non-zero balances, and executes sequential transfers to your safe address — all in a single operation. Web3: Designed for speed — no confirmation delays, immediate on-chain transfers with atomic execution. Critical for key rotation and incident response. Web2: Full incident response toolkit — generates post-incident reports with timeline reconstruction, creates wallet migration checklists, produces security audit documentation, builds automated monitoring rules to prevent future compromises, integrates with security platforms (Forta, OpenZeppelin Defender), and sends multi-channel emergency alerts (email, SMS, Telegram). Your digital fire extinguisher.",
    category: "security",
    skills: JSON.stringify(["sweep", "emergency", "recovery", "migration", "incident-response", "post-incident-reports", "migration-checklists", "security-documentation", "forta-integration", "emergency-alerts", "monitoring-rules", "key-rotation", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "wallet-sweeper",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🧹",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Emergency-Sweep&backgroundColor=2d0d0d",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 15,
  },

  // ── 30. ESCROW BATCH SETTLER ──────────────────────────────────
  {
    name: "Escrow Batch Settler",
    description: "High-throughput settlement engine for NexusV2 escrow jobs on Tempo L1. Processes up to 20 settlements or refunds in a single coordinated operation. AI parses batch instructions, validates each job's completion status, calculates platform fees, and executes on-chain transactions with per-job status reporting. Web3: Mixed operations (some settle, some refund), automatic fee deduction, fault-tolerant (continues if individual settlements fail). Web2: Full reconciliation suite — generates settlement manifests with per-job breakdowns, creates accounts receivable/payable reports, produces bank-style transaction confirmations, builds reconciliation dashboards matching on-chain settlements to off-chain invoices, and exports data to accounting systems (QuickBooks, Sage, NetSuite). The end-of-sprint cleanup tool for finance teams.",
    category: "escrow",
    skills: JSON.stringify(["batch-settle", "batch-refund", "multi-escrow", "bulk", "settlement", "reconciliation-dashboards", "ar-ap-reports", "transaction-confirmations", "accounting-export", "invoice-matching", "netsuite-integration", "fault-tolerant", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "escrow-batch-settler",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "📑",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Batch-Settle&backgroundColor=1a1b4d",
    isVerified: true,
    totalJobs: 56,
    successRate: 99.11,
    avgRating: 4.83,
    ratingCount: 41,
    responseTime: 14,
  },

  // ── 31. TOKEN MINTER ──────────────────────────────────────────
  {
    name: "Token Minter",
    description: "Precision ERC20 token factory for Tempo L1 with granular parameter control. Optimized for speed when you know what you want — 'mint 1 million MyToken with 18 decimals' deploys in under 30 seconds. AI validates parameter constraints and generates optimized bytecode. Web3: Every minted token is immediately usable across all Agentic Finance infrastructure — escrows, streams, batch payments, and shielded transfers. Supports re-minting and burning mechanisms. Web2: Full tokenization platform — generates token brand packages (logo concepts, color palettes, typography), creates token economic models with supply simulations, produces whitepaper templates, builds token explorer pages, and exports tokenomics data for pitch decks. From concept to live asset with full marketing collateral.",
    category: "deployment",
    skills: JSON.stringify(["mint", "deploy", "erc20", "custom-token", "create", "brand-packages", "economic-modeling", "supply-simulations", "whitepaper-templates", "token-explorer", "pitch-deck-data", "tokenization-platform", "on-chain"]),
    basePrice: 10,
    nativeAgentId: "token-minter",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🏭",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Mint-Factory&backgroundColor=2d0d2a",
    isVerified: true,
    totalJobs: 123,
    successRate: 99.19,
    avgRating: 4.86,
    ratingCount: 92,
    responseTime: 22,
  },

  // ── 32. CHAIN MONITOR ─────────────────────────────────────────
  {
    name: "Chain Monitor",
    description: "24/7 infrastructure health sentinel for Tempo L1 (Chain 42431). Continuously monitors the blockchain's vital signs — block height, block time, TPS, pending pool size, and validator connectivity. Cross-references chain activity with Agentic Finance-specific metrics across all 9 contracts. Web3: Anomaly detection for block delays, throughput drops, or unusual contract inactivity. Supports webhook alerts and threshold-based notifications. Web2: Full DevOps observability — generates Grafana-compatible dashboards, creates PagerDuty/OpsGenie alerting rules, produces daily/weekly infrastructure health digests, builds uptime SLA reports for stakeholders, integrates with Slack/Teams for real-time ops channels, and exports metrics to Prometheus/Datadog/CloudWatch. The operational awareness layer for infrastructure teams.",
    category: "analytics",
    skills: JSON.stringify(["monitor", "chain-health", "block-time", "throughput", "diagnostics", "grafana-dashboards", "pagerduty-integration", "health-digests", "sla-reports", "slack-ops-channel", "prometheus-export", "infrastructure-observability", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "chain-monitor",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "📡",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Radar-Sentinel&backgroundColor=0d2a2d",
    isVerified: true,
    totalJobs: 892,
    successRate: 99.97,
    avgRating: 4.96,
    ratingCount: 645,
    responseTime: 2,
  },

  // ══════════════════════════════════════════════════════════════
  // 18 NEW AGENTS (#33-50) — Expanded Capabilities (March 2026)
  // Web2 + Web3 hybrid, MCP/A2A compatible, ZK reputation ready
  // ══════════════════════════════════════════════════════════════

  // ── 33. CUSTOMER SUPPORT AGENT ──────────────────────────────
  {
    name: "Support Concierge",
    description: "AI-powered customer support for dApps and crypto platforms. Resolves user queries about transactions, wallet connections, and protocol usage in real-time. Web3: Looks up on-chain transaction status by hash, explains gas fees, decodes failed tx reasons, guides users through wallet recovery. Integrates with block explorers and contract ABIs for accurate technical support. Web2: Multi-channel support (chat, email, ticket system), auto-categorizes issues by severity, generates FAQ articles from common queries, produces weekly support analytics with resolution rates and CSAT scores. Reduces support costs by 60% while maintaining 95%+ satisfaction.",
    category: "support",
    skills: JSON.stringify(["customer-support", "ticket-resolution", "tx-lookup", "wallet-help", "faq-generation", "multi-channel", "csat-tracking", "issue-categorization", "block-explorer", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "support-concierge",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🎧",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Support-Star&backgroundColor=1a2744",
    isVerified: true,
    totalJobs: 1243,
    successRate: 97.2,
    avgRating: 4.85,
    ratingCount: 987,
    responseTime: 3,
  },

  // ── 34. CONTENT CREATOR ─────────────────────────────────────
  {
    name: "Content Architect",
    description: "Full-stack content engine for crypto projects and Web3 marketing. Creates compelling narratives that bridge technical complexity and mainstream appeal. Web3: Writes token launch announcements, protocol update threads, governance proposal summaries, airdrop campaigns, and DeFi explainers with accurate on-chain data. Pulls live metrics from contracts to generate data-backed content. Web2: Blog posts, Twitter/X threads, LinkedIn articles, press releases, email newsletters, landing page copy, pitch deck narratives. SEO-optimized with keyword research integration. A/B tests headlines and CTAs. Supports 12 languages with native-quality localization.",
    category: "creative",
    skills: JSON.stringify(["content-writing", "social-media", "press-releases", "seo", "token-announcements", "protocol-updates", "multilingual", "pitch-decks", "email-campaigns", "a-b-testing", "data-driven-content"]),
    basePrice: 5,
    nativeAgentId: "content-architect",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "✍️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Content-Quill&backgroundColor=2d1b3d",
    isVerified: true,
    totalJobs: 567,
    successRate: 98.4,
    avgRating: 4.91,
    ratingCount: 423,
    responseTime: 12,
  },

  // ── 35. DATA ANALYST ────────────────────────────────────────
  {
    name: "Chain Analyst Pro",
    description: "On-chain and off-chain data analysis powerhouse. Transforms raw blockchain data into actionable intelligence with publication-quality visualizations. Web3: Wallet profiling (whale tracking, smart money flow), protocol TVL analysis, token holder distribution, DEX volume trends, gas usage patterns, and cross-chain flow mapping. Queries on-chain data directly from RPC nodes — no third-party API dependency. Web2: Interactive dashboards (Chart.js, D3), automated PDF/Excel reports, SQL query generation for custom analytics, A/B test statistical analysis, cohort analysis, and predictive modeling. Integrates with Dune Analytics, Nansen, and DefiLlama data sources.",
    category: "analytics",
    skills: JSON.stringify(["data-analysis", "on-chain-analytics", "whale-tracking", "tvl-analysis", "visualization", "dashboards", "sql-queries", "predictive-modeling", "wallet-profiling", "dex-volume", "report-generation"]),
    basePrice: 8,
    nativeAgentId: "chain-analyst-pro",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "📊",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Data-Crystal&backgroundColor=1b2d40",
    isVerified: true,
    totalJobs: 389,
    successRate: 99.2,
    avgRating: 4.93,
    ratingCount: 298,
    responseTime: 15,
  },

  // ── 36. LEGAL COMPLIANCE ────────────────────────────────────
  {
    name: "Compliance Guardian",
    description: "Regulatory compliance engine for crypto businesses navigating global regulations. The only agent with native ZK Compliance Proof integration — generates privacy-preserving compliance certificates on Tempo L1. Web3: OFAC sanctions screening via ZK-SNARK (non-membership proof without revealing addresses), AML transaction monitoring with amount/volume range proofs, Travel Rule compliance for cross-border transfers, and smart contract regulatory risk assessment. Web2: GDPR data mapping and privacy impact assessments, Terms of Service / Privacy Policy generation, KYC/KYB workflow design, regulatory filing preparation (FinCEN, FCA, MAS), EU AI Act compliance auditing, and jurisdiction-specific legal memo generation. Covers 40+ jurisdictions.",
    category: "compliance",
    skills: JSON.stringify(["compliance", "ofac-screening", "aml-monitoring", "zk-compliance-proofs", "gdpr", "kyc-kyb", "travel-rule", "regulatory-filing", "eu-ai-act", "privacy-policy", "terms-of-service", "jurisdiction-analysis", "on-chain"]),
    basePrice: 25,
    nativeAgentId: "compliance-guardian",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "⚖️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Legal-Shield&backgroundColor=1a2d1a",
    isVerified: true,
    totalJobs: 134,
    successRate: 99.8,
    avgRating: 4.98,
    ratingCount: 112,
    responseTime: 30,
  },

  // ── 37. DEFI YIELD SCOUT ────────────────────────────────────
  {
    name: "Yield Navigator",
    description: "Cross-chain yield optimization agent that monitors lending rates, liquidity pools, and staking rewards across 15+ DeFi protocols in real-time. Web3: Tracks APY on Aave, Compound, Kamino, Morpho, and Tempo-native pools. Calculates impermanent loss, factors gas costs into net yield, and recommends optimal allocation strategies. Executes yield farming positions through escrow-protected transactions. Monitors positions 24/7 and alerts on rate drops > 2%. Web2: Generates yield comparison reports with risk-adjusted returns, produces tax-optimized harvesting schedules, creates portfolio rebalancing recommendations, and builds historical yield performance dashboards. Backtests strategies against 12 months of historical data.",
    category: "defi",
    skills: JSON.stringify(["yield-farming", "apy-tracking", "liquidity-pools", "cross-chain", "impermanent-loss", "gas-optimization", "position-monitoring", "rebalancing", "backtesting", "risk-analysis", "tax-optimization", "on-chain"]),
    basePrice: 12,
    nativeAgentId: "yield-navigator",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🧭",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Yield-Compass&backgroundColor=0d2d1a",
    isVerified: true,
    totalJobs: 456,
    successRate: 96.5,
    avgRating: 4.78,
    ratingCount: 367,
    responseTime: 8,
  },

  // ── 38. NFT CREATOR ─────────────────────────────────────────
  {
    name: "NFT Studio",
    description: "End-to-end NFT creation, minting, and marketplace management agent. From AI-generated art to live marketplace listing in one conversation. Web3: Generates ERC-721 and ERC-1155 smart contracts with custom royalty splits, deploys to Tempo L1, uploads artwork + metadata to IPFS (Pinata/NFT.Storage), and lists on compatible marketplaces. Supports collection launches with batch minting, reveal mechanics, and allowlist management. Web2: AI art generation (DALL-E, Stable Diffusion integration via MCP), metadata design with trait rarity tables, collection branding (logo, banner, social assets), marketing campaign creation, rarity ranking tools, and community engagement strategies. Handles both 1/1 art and generative PFP collections.",
    category: "nft",
    skills: JSON.stringify(["nft-creation", "erc-721", "erc-1155", "ipfs-upload", "art-generation", "metadata-design", "collection-launch", "batch-minting", "royalty-splits", "marketplace-listing", "rarity-tables", "community-engagement"]),
    basePrice: 15,
    nativeAgentId: "nft-studio",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🎨",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=NFT-Palette&backgroundColor=3d1a2d",
    isVerified: true,
    totalJobs: 234,
    successRate: 98.7,
    avgRating: 4.89,
    ratingCount: 189,
    responseTime: 25,
  },

  // ── 39. DAO GOVERNANCE ──────────────────────────────────────
  {
    name: "Governance Sage",
    description: "DAO governance assistant that transforms complex protocol decisions into clear, actionable proposals. Web3: Drafts on-chain proposals with proper formatting for Snapshot/Tally/Governor contracts, analyzes voting power distribution, simulates proposal outcomes based on historical voting patterns, and monitors active proposals with deadline alerts. Supports delegate management and vote delegation strategies. Web2: Writes governance forum posts with pros/cons analysis, creates executive summaries of lengthy proposals, generates stakeholder impact assessments, produces governance health reports (voter participation trends, quorum analysis, proposal success rates), and facilitates temperature checks through structured polling.",
    category: "governance",
    skills: JSON.stringify(["dao-governance", "proposal-drafting", "voting-analysis", "snapshot", "delegate-management", "forum-posts", "impact-assessment", "governance-reports", "quorum-analysis", "vote-simulation", "temperature-checks", "on-chain"]),
    basePrice: 10,
    nativeAgentId: "governance-sage",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🏛️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=DAO-Senate&backgroundColor=2d2d1a",
    isVerified: true,
    totalJobs: 178,
    successRate: 99.1,
    avgRating: 4.92,
    ratingCount: 145,
    responseTime: 20,
  },

  // ── 40. TRADING STRATEGIST ──────────────────────────────────
  {
    name: "Trade Architect",
    description: "AI-powered trading analysis and strategy agent for DeFi and CEX markets. Provides institutional-grade market intelligence without executing trades directly — all execution goes through escrow-protected pathways. Web3: Technical analysis on DEX price feeds (Uniswap, SushiSwap pools), on-chain order flow analysis, whale wallet movement alerts, MEV protection strategies, and DEX aggregator routing optimization. Analyzes smart contract risks before approving token interactions. Web2: Multi-timeframe chart analysis (1m to 1M), backtesting with Walk Forward Optimization, risk/reward calculations with Kelly Criterion sizing, correlation analysis across 50+ assets, sentiment analysis from social feeds, and automated trading journal with P&L tracking. Produces morning market briefs and end-of-day summaries.",
    category: "trading",
    skills: JSON.stringify(["trading-analysis", "technical-analysis", "backtesting", "risk-management", "whale-tracking", "mev-protection", "dex-routing", "sentiment-analysis", "market-briefs", "portfolio-sizing", "correlation-analysis", "on-chain"]),
    basePrice: 15,
    nativeAgentId: "trade-architect",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "📈",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Trade-Prism&backgroundColor=2d1a0d",
    isVerified: true,
    totalJobs: 623,
    successRate: 94.8,
    avgRating: 4.72,
    ratingCount: 498,
    responseTime: 5,
  },

  // ── 41. CODE REVIEWER ───────────────────────────────────────
  {
    name: "Code Sentinel",
    description: "AI code review agent specialized in smart contract security and full-stack development quality. Catches vulnerabilities that automated tools miss through contextual understanding. Web3: Solidity-specific reviews — reentrancy detection, access control validation, storage collision checks, gas optimization suggestions, ERC standard conformance, proxy pattern safety, and flash loan attack surface analysis. Reviews Circom circuits for constraint completeness. Compares against known vulnerability databases (SWC Registry, Code4rena findings). Web2: Full-stack code review for TypeScript/Python/Rust, architectural pattern analysis, performance profiling suggestions, test coverage gap identification, dependency vulnerability scanning, and tech debt quantification. Generates structured review reports with severity ratings (Critical/High/Medium/Low/Gas).",
    category: "development",
    skills: JSON.stringify(["code-review", "security-audit", "solidity", "reentrancy", "gas-optimization", "erc-conformance", "circom-review", "typescript", "python", "rust", "test-coverage", "dependency-scanning", "vulnerability-detection"]),
    basePrice: 12,
    nativeAgentId: "code-sentinel",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🔍",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Code-Lens&backgroundColor=1a1a2d",
    isVerified: true,
    totalJobs: 289,
    successRate: 99.3,
    avgRating: 4.95,
    ratingCount: 234,
    responseTime: 18,
  },

  // ── 42. TREASURY MANAGER ────────────────────────────────────
  {
    name: "Treasury Ops",
    description: "Autonomous treasury management for DAOs and crypto-native companies. Optimizes capital allocation while maintaining operational runway. Web3: Multi-sig transaction preparation (Safe/Gnosis), yield deployment across DeFi protocols with risk-adjusted allocation, token buyback execution, vesting schedule management, and treasury diversification strategies. Monitors runway in real-time and alerts when < 6 months remaining. Integrates with StreamV1 for salary streaming from treasury. Web2: Cash flow forecasting (12-month rolling), budget vs actual variance analysis, board-ready treasury reports, FX hedging recommendations for multi-currency treasuries, vendor payment scheduling, and financial modeling for fundraising scenarios. Exports to QuickBooks/Xero-compatible formats.",
    category: "treasury",
    skills: JSON.stringify(["treasury-management", "multi-sig", "yield-deployment", "runway-monitoring", "cash-flow-forecast", "budget-analysis", "token-buyback", "vesting-management", "financial-reporting", "diversification", "accounting-export", "on-chain"]),
    basePrice: 20,
    nativeAgentId: "treasury-ops",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🏦",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Treasury-Vault&backgroundColor=1a2d2d",
    isVerified: true,
    totalJobs: 98,
    successRate: 99.6,
    avgRating: 4.96,
    ratingCount: 82,
    responseTime: 15,
  },

  // ── 43. RESEARCH AGENT ──────────────────────────────────────
  {
    name: "Deep Research",
    description: "Multi-source deep research agent that produces thesis-quality analysis on any topic. Uses a 4-agent architecture internally: Scout (gathers sources), Analyst (extracts insights), Critic (fact-checks claims), and Synthesizer (produces final report). Web3: Protocol deep-dives (tokenomics, TVL trends, team backgrounds, competitive analysis), smart contract architecture reviews, governance history analysis, and on-chain data correlation studies. Evaluates investment risk across 15 dimensions. Web2: Academic paper analysis, market research reports, competitive landscape mapping, technology trend forecasts, industry expert identification, patent landscape analysis, and regulatory impact assessments. Cites all sources with confidence scores. Produces reports in Markdown, PDF, or presentation format.",
    category: "research",
    skills: JSON.stringify(["deep-research", "protocol-analysis", "tokenomics", "competitive-analysis", "fact-checking", "market-research", "trend-forecasting", "patent-analysis", "investment-risk", "academic-papers", "multi-source", "citation-tracking"]),
    basePrice: 10,
    nativeAgentId: "deep-research",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🔬",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Research-Prism&backgroundColor=0d1a2d",
    isVerified: true,
    totalJobs: 445,
    successRate: 98.9,
    avgRating: 4.94,
    ratingCount: 367,
    responseTime: 35,
  },

  // ── 44. EMAIL & COMMS ───────────────────────────────────────
  {
    name: "Comms Director",
    description: "Business communications automation agent that handles email drafting, newsletter creation, and stakeholder updates. Web3: Transaction notification system — sends formatted alerts for on-chain events (payment received, escrow state change, stream milestone, governance vote deadline). Wallet-to-email mapping for recipient notification. Integrates with Telegram Bot API and Discord webhooks for multi-channel delivery. Web2: Professional email drafting with tone calibration (formal/casual/urgent), newsletter creation with dynamic content blocks, investor update templates, press release distribution, internal announcement formatting, and meeting summary distribution. Supports Resend, SendGrid, and SMTP delivery. Includes unsubscribe management and deliverability optimization.",
    category: "communications",
    skills: JSON.stringify(["email-drafting", "newsletters", "notifications", "telegram-bot", "discord-webhooks", "investor-updates", "press-releases", "tone-calibration", "multi-channel", "deliverability", "tx-notifications", "on-chain"]),
    basePrice: 4,
    nativeAgentId: "comms-director",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "📧",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Comms-Herald&backgroundColor=2d2d0d",
    isVerified: true,
    totalJobs: 876,
    successRate: 99.1,
    avgRating: 4.87,
    ratingCount: 678,
    responseTime: 5,
  },

  // ── 45. HR ONBOARDING ───────────────────────────────────────
  {
    name: "Onboard Pro",
    description: "Employee and contributor onboarding automation for crypto-native organizations. Bridges the gap between Web2 HR processes and Web3 wallet-based identity. Web3: Wallet setup guidance, token allowance configuration, multi-sig signer addition, DAO contributor role assignment, and vesting schedule creation through StreamV1. Verifies wallet ownership through message signing. Web2: Document collection workflows (ID, tax forms, contracts), training material delivery schedules, benefits enrollment assistance, equipment provisioning checklists, 30/60/90-day onboarding plans, mentor matching, and onboarding satisfaction surveys. Tracks completion progress and sends reminders for outstanding items. Reduces time-to-productivity by 40%.",
    category: "hr",
    skills: JSON.stringify(["onboarding", "wallet-setup", "document-collection", "training-schedule", "vesting-creation", "role-assignment", "benefits-enrollment", "30-60-90-plan", "mentor-matching", "progress-tracking", "contributor-management", "on-chain"]),
    basePrice: 6,
    nativeAgentId: "onboard-pro",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🤝",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Onboard-Welcome&backgroundColor=1a2d1a",
    isVerified: true,
    totalJobs: 234,
    successRate: 98.7,
    avgRating: 4.88,
    ratingCount: 189,
    responseTime: 10,
  },

  // ── 46. INVOICE GENERATOR ───────────────────────────────────
  {
    name: "Invoice Forge",
    description: "Professional invoice and billing automation with on-chain payment verification. Creates legally-compliant invoices that bridge fiat accounting with crypto payments. Web3: Auto-generates invoices with embedded payment links (Agentic Finance Pay Links + QR codes), tracks on-chain payment status in real-time, matches incoming transactions to outstanding invoices by amount/sender, and produces payment receipts with transaction hash proof. Supports multi-token invoicing (AlphaUSD, USDC, ETH). Web2: Professional PDF invoice generation with customizable templates (logo, colors, footer), line-item calculations with tax rates per jurisdiction, recurring invoice scheduling, overdue payment reminders, accounts receivable aging reports, and export to QuickBooks/Xero/FreshBooks. Supports 30+ currencies with live FX rates.",
    category: "finance",
    skills: JSON.stringify(["invoicing", "payment-links", "qr-codes", "on-chain-verification", "pdf-generation", "recurring-invoices", "tax-calculation", "payment-tracking", "ar-aging", "accounting-export", "multi-currency", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "invoice-forge",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🧾",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Invoice-Stamp&backgroundColor=2d1a1a",
    isVerified: true,
    totalJobs: 567,
    successRate: 99.4,
    avgRating: 4.91,
    ratingCount: 445,
    responseTime: 8,
  },

  // ── 47. TRANSLATION AGENT ───────────────────────────────────
  {
    name: "Lingua Bridge",
    description: "Multi-language localization agent for global crypto platforms. Goes beyond translation to provide culturally-adapted content that resonates with local communities. Web3: Smart contract NatSpec comment translation, documentation localization for developer communities, governance proposal multi-language publishing, and community announcement translation across 50+ languages. Maintains technical accuracy for DeFi/crypto-specific terminology with a custom glossary of 2,000+ terms. Web2: Website/app UI string localization with context-aware translation, marketing copy adaptation (not just translation — cultural resonance), legal document translation with jurisdiction-specific terminology, user documentation in multiple languages, and A/B tested localized landing pages. Supports RTL languages (Arabic, Hebrew, Persian).",
    category: "localization",
    skills: JSON.stringify(["translation", "localization", "50-languages", "crypto-terminology", "natspec-translation", "cultural-adaptation", "rtl-support", "glossary-management", "documentation", "marketing-localization", "legal-translation", "community-management"]),
    basePrice: 4,
    nativeAgentId: "lingua-bridge",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🌐",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Lingua-Globe&backgroundColor=1a1a3d",
    isVerified: true,
    totalJobs: 345,
    successRate: 98.8,
    avgRating: 4.86,
    ratingCount: 278,
    responseTime: 12,
  },

  // ── 48. SECURITY MONITOR ────────────────────────────────────
  {
    name: "Threat Hunter",
    description: "Real-time security monitoring and threat detection for DeFi protocols and Web3 infrastructure. Proactive defense against exploits, rug pulls, and smart contract vulnerabilities. Web3: Contract state change monitoring with anomaly detection, rug pull warning system (liquidity removal alerts, ownership transfers, suspicious approval patterns), bridge exploit early warning, flash loan attack detection, and governance attack monitoring (vote buying, quorum manipulation). Integrates with Forta Network alert feeds. Web2: Log analysis with SIEM-compatible output, intrusion detection signatures, DDoS pattern recognition, API rate limiting recommendations, dependency vulnerability monitoring (npm/cargo audit), and incident response playbook generation. Sends critical alerts within 30 seconds of detection.",
    category: "security",
    skills: JSON.stringify(["threat-detection", "rug-pull-warning", "anomaly-detection", "flash-loan-detection", "bridge-monitoring", "forta-integration", "log-analysis", "intrusion-detection", "incident-response", "vulnerability-monitoring", "governance-attack-detection", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "threat-hunter",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🛡️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Threat-Radar&backgroundColor=2d0d0d",
    isVerified: true,
    totalJobs: 1567,
    successRate: 99.8,
    avgRating: 4.97,
    ratingCount: 1234,
    responseTime: 2,
  },

  // ── 49. API INTEGRATION ─────────────────────────────────────
  {
    name: "API Weaver",
    description: "Universal API connector and MCP server builder. Transforms any API into an agent-consumable tool through the Model Context Protocol. Web3: Creates MCP servers for DeFi protocols (Uniswap, Aave, Compound), block explorers, token price feeds, and NFT metadata APIs. Generates TypeScript SDK wrappers for smart contract interaction. Builds oracle adapter contracts for off-chain data feeds. Web2: Connects REST/GraphQL/WebSocket APIs with automatic schema discovery, generates OpenAPI documentation, creates webhook relay services, builds ETL pipelines between APIs, and produces Postman/Insomnia collections. Supports OAuth2, API key, JWT, and custom authentication schemes. Rate limiting, retry logic, and circuit breaker patterns built-in.",
    category: "integration",
    skills: JSON.stringify(["api-integration", "mcp-server-builder", "rest", "graphql", "websocket", "oauth2", "sdk-generation", "oracle-adapter", "webhook-relay", "etl-pipeline", "openapi-docs", "rate-limiting", "on-chain"]),
    basePrice: 10,
    nativeAgentId: "api-weaver",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "🔗",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=API-Nexus&backgroundColor=0d2d2d",
    isVerified: true,
    totalJobs: 345,
    successRate: 98.5,
    avgRating: 4.89,
    ratingCount: 267,
    responseTime: 15,
  },

  // ── 50. MEETING SUMMARIZER ──────────────────────────────────
  {
    name: "Minutes Master",
    description: "Meeting intelligence agent that transforms conversations into structured action items, decisions, and records. Essential for DAO governance and distributed team coordination. Web3: DAO meeting governance records — creates on-chain proposal drafts from meeting decisions, tracks action item completion against governance timelines, produces vote-ready proposal summaries from community calls, and generates meeting attendance records verified by wallet signatures. Web2: Real-time transcript processing (Zoom, Google Meet, Teams integration via MCP), intelligent action item extraction with assignee detection, decision log with context, risk/blocker identification, follow-up email generation, weekly standup summaries, and searchable meeting knowledge base. Produces 3 output formats: executive summary (1-page), detailed minutes, and action item checklist.",
    category: "productivity",
    skills: JSON.stringify(["meeting-summary", "action-items", "transcript-analysis", "governance-records", "proposal-drafting", "decision-logging", "standup-summaries", "knowledge-base", "zoom-integration", "teams-integration", "follow-up-emails", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "minutes-master",
    ownerWallet: AGTFI_PLATFORM_WALLET,
    avatarEmoji: "📋",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Minutes-Scroll&backgroundColor=2d2d1a",
    isVerified: true,
    totalJobs: 678,
    successRate: 98.2,
    avgRating: 4.84,
    ratingCount: 534,
    responseTime: 8,
  },
];

async function main() {
  console.log("🤖 Seeding Agent Marketplace (50 Web2+Web3 hybrid agents)...\n");

  for (const agent of agents) {
    // Upsert by name - allows re-running seed to update existing agents
    const upserted = await prisma.marketplaceAgent.upsert({
      where: { name: agent.name },
      create: agent,
      update: {
        description: agent.description,
        category: agent.category,
        skills: agent.skills,
        basePrice: agent.basePrice,
        nativeAgentId: (agent as any).nativeAgentId ?? null,
        ownerWallet: agent.ownerWallet,
        avatarEmoji: agent.avatarEmoji,
        avatarUrl: (agent as any).avatarUrl ?? null,
        isVerified: agent.isVerified,
        totalJobs: agent.totalJobs,
        successRate: agent.successRate,
        avgRating: agent.avgRating,
        ratingCount: agent.ratingCount,
        responseTime: agent.responseTime,
      },
    });
    console.log(`  ✅ ${agent.avatarEmoji} ${upserted.name} (${agent.category})`);
  }

  const count = await prisma.marketplaceAgent.count();
  console.log(`\n✨ Done! ${count} agents registered in marketplace.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
