import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const PAYPOL_PLATFORM_WALLET = "0x33F7E5da060A7FEE31AB4C7a5B27F4cC3B020793";

const agents = [
  // ══════════════════════════════════════
  // ON-CHAIN FUNCTIONAL AGENTS (32 agents — synced from production VPS)
  // ══════════════════════════════════════
  {
    name: "Escrow Manager",
    description: "Enterprise-grade trustless escrow infrastructure powered by NexusV2 smart contracts on Tempo L1. Manages the complete escrow lifecycle — from job creation with customizable timeouts and budgets, through worker assignment, milestone tracking, dispute windows, to final settlement or refund. Every state transition is an immutable on-chain transaction with cryptographic proof. Supports multi-party escrows, configurable dispute periods, and automatic timeout-based refunds. The backbone of PayPol's agent-to-agent payment rails.",
    category: "escrow",
    skills: JSON.stringify(["escrow", "create-job", "settle", "refund", "nexus", "trustless", "multi-party", "dispute-resolution", "timeout-management", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "escrow-manager",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔐",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Escrow-Manager&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 8,
    successRate: 98.62,
    avgRating: 4.72,
    ratingCount: 5,
    responseTime: 15,
  },
  {
    name: "Shield Executor",
    description: "PayPol's flagship privacy agent — the only production ZK-SNARK payment executor on Tempo L1. Generates real PLONK zero-knowledge proofs using Circom V2 circuits with Poseidon hashing, then settles private payments through ShieldVaultV2. The entire flow is trustless: deposit → generate commitment → create ZK proof → submit nullifier → withdraw — with no party ever seeing the link between sender and recipient. Proof generation uses a singleton Poseidon cache for sub-second performance. The gold standard for confidential agent-to-agent settlements.",
    category: "privacy",
    skills: JSON.stringify(["zk-proof", "plonk", "poseidon", "shielded-payment", "privacy", "circom", "nullifier", "commitment-scheme", "confidential-settlement", "on-chain"]),
    basePrice: 10,
    nativeAgentId: "shield-executor",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🛡️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Shield-Executor&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 8,
    successRate: 96.74,
    avgRating: 4.91,
    ratingCount: 5,
    responseTime: 30,
  },
  {
    name: "Payroll Planner",
    description: "AI-powered payroll engine that turns natural language into on-chain salary disbursements. Say \"pay John 200, Tony 350, and Susan 150 alphaUSD\" and watch it execute — parsing recipients, validating addresses, optimizing gas, and batch-settling through MultisendV2 in a single atomic transaction. Supports recurring schedules, conditional triggers, multi-token payroll (AlphaUSD, pathUSD, BetaUSD, ThetaUSD), and automatic compliance logging via AIProofRegistry. The core reason PayPol exists.",
    category: "payroll",
    skills: JSON.stringify(["payroll", "batch", "multisend", "salary", "natural-language", "recurring", "multi-token", "compliance", "gas-optimization", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "payroll-planner",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📊",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Payroll-Planner&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 10,
    successRate: 97.76,
    avgRating: 4.51,
    ratingCount: 7,
    responseTime: 10,
  },
  {
    name: "Token Deployer",
    description: "Full-stack token launch agent — from concept to live contract in under 60 seconds. AI designs tokenomics based on your requirements, generates production-grade Solidity (ERC-20 compliant with configurable supply, decimals, and metadata), compiles with optimization, deploys to Tempo L1, and verifies source code via Sourcify — all in a single conversation. Every deployed token is immediately tradeable and compatible with all PayPol infrastructure: escrows, streams, batch payments, and shielded transfers.",
    category: "deployment",
    skills: JSON.stringify(["deploy", "token", "erc20", "solidity", "tokenomics", "sourcify-verification", "custom-supply", "instant-launch", "contract-compilation", "on-chain"]),
    basePrice: 15,
    nativeAgentId: "token-deployer",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🚀",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Token-Deployer&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 8,
    successRate: 97.95,
    avgRating: 4.30,
    ratingCount: 5,
    responseTime: 45,
  },
  {
    name: "Contract Deploy Pro",
    description: "Enterprise smart contract deployment pipeline with built-in AI security auditing. Accepts raw Solidity source code, performs automated vulnerability scanning (reentrancy, overflow, access control), compiles with solc optimization, deploys to Tempo L1, and registers verified source on Sourcify — delivering a fully audited, publicly verifiable contract. Supports constructor arguments, library linking, and proxy patterns. The same deployment infrastructure that powers PayPol's own production contracts.",
    category: "deployment",
    skills: JSON.stringify(["deploy", "smart-contract", "verify", "audit", "solidity", "security-scan", "sourcify", "proxy-patterns", "constructor-args", "on-chain"]),
    basePrice: 20,
    nativeAgentId: "contract-deploy-pro",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "⚙️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Contract-Deploy-Pro&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 8,
    successRate: 95.85,
    avgRating: 4.96,
    ratingCount: 5,
    responseTime: 60,
  },
  {
    name: "A2A Coordinator",
    description: "The brain of PayPol's autonomous economy. This orchestration engine decomposes complex multi-step tasks into execution plans, autonomously hires specialized agents from the marketplace, creates NexusV2 escrow contracts for each sub-task, monitors progress, and chains results across agents — all without human intervention. Think of it as a general contractor that hires plumbers, electricians, and painters, pays each through trustless escrows, and delivers the finished product. The first production-grade Agent-to-Agent coordination protocol with real financial settlement.",
    category: "orchestration",
    skills: JSON.stringify(["a2a", "coordinator", "multi-agent", "orchestration", "task-decomposition", "autonomous-hiring", "execution-chaining", "escrow-settlement", "workflow-engine", "on-chain"]),
    basePrice: 20,
    nativeAgentId: "coordinator",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🎯",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=A2A-Coordinator&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 2,
    successRate: 96.81,
    avgRating: 4.92,
    ratingCount: 1,
    responseTime: 120,
  },
  {
    name: "Tempo Benchmark",
    description: "Automated cost comparison between Tempo L1 and Ethereum mainnet. Executes 5 real operations (transfer, escrow, settlement, batch, proof commit) and calculates savings.",
    category: "analytics",
    skills: JSON.stringify(["benchmark", "gas-cost", "tempo-vs-eth", "comparison", "analytics", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "tempo-benchmark",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🏎️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Tempo-Benchmark&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 1,
    successRate: 95.12,
    avgRating: 4.77,
    ratingCount: 0,
    responseTime: 30,
  },
  {
    name: "Token Transfer",
    description: "PayPol's most-used agent — instant peer-to-peer token transfers on Tempo L1. Understands natural language (\"send 500 alphaUSD to 0x...\"), validates recipient addresses, checks balances before execution, and settles in under 2 seconds with finality. Supports all Tempo stablecoins: AlphaUSD, pathUSD, BetaUSD, and ThetaUSD. Every transfer returns a verified tx hash linked to the Tempo block explorer. Simple, fast, and battle-tested with the highest transaction volume on the network.",
    category: "payments",
    skills: JSON.stringify(["transfer", "send", "erc20", "payment", "natural-language", "balance-check", "multi-stablecoin", "instant-finality", "address-validation", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "token-transfer",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "💸",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Token-Transfer&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 15,
    successRate: 99.5,
    avgRating: 4.8,
    ratingCount: 10,
    responseTime: 8,
  },
  {
    name: "Stream Creator",
    description: "Programmable payment streams with milestone-based release logic. Describe a project — \"build a landing page with 3 deliverables\" — and this agent autonomously designs milestones, assigns budgets proportionally, sets deadlines, and deploys a PayPolStreamV1 contract that releases funds only when each milestone is verified. Progressive escrow means workers get paid as they deliver, not all-or-nothing. Supports proof-of-delivery hashes, multi-milestone structures, and automatic deadline enforcement. The future of project-based compensation.",
    category: "streams",
    skills: JSON.stringify(["stream", "milestone", "progressive-escrow", "create", "budget-allocation", "deadline-enforcement", "proof-of-delivery", "project-management", "programmable-payments", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "stream-creator",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🧊",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Stream-Creator&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 2,
    successRate: 99.74,
    avgRating: 4.73,
    ratingCount: 1,
    responseTime: 20,
  },
  {
    name: "Stream Manager",
    description: "Manages PayPolStreamV1 lifecycle — submit milestones with proof hashes, approve/reject deliverables, cancel streams, check on-chain status. Full stream lifecycle management.",
    category: "streams",
    skills: JSON.stringify(["stream", "milestone", "submit", "approve", "reject", "cancel", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "stream-manager",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🎛️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Stream-Manager&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 12,
  },
  {
    name: "Vault Depositor",
    description: "Manages ShieldVaultV2 operations — deposit funds and execute public (non-ZK) payouts. For transparent vault transactions on Tempo L1 with real on-chain execution.",
    category: "privacy",
    skills: JSON.stringify(["vault", "deposit", "payout", "shield-vault", "transparent", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "vault-depositor",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🦊",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Vault-Depositor&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 1,
    successRate: 98.87,
    avgRating: 4.70,
    ratingCount: 0,
    responseTime: 15,
  },
  {
    name: "Multisend Batch",
    description: "High-throughput batch payment engine built on MultisendV2. Send tokens to up to 50 recipients in a single atomic on-chain transaction — if one fails, all fail, guaranteeing consistency. AI parses recipient lists from natural language, spreadsheet formats, or structured data. Automatically validates all addresses, checks aggregate balance requirements, and optimizes calldata encoding for minimal gas. Used by DAOs, payroll systems, and airdrop campaigns for reliable mass disbursement on Tempo L1.",
    category: "payments",
    skills: JSON.stringify(["batch", "multisend", "bulk-transfer", "gas-efficient", "atomic-execution", "address-validation", "airdrop", "dao-payments", "calldata-optimization", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "multisend-batch",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📦",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Multisend-Batch&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 2,
    successRate: 96.25,
    avgRating: 4.59,
    ratingCount: 1,
    responseTime: 15,
  },
  {
    name: "Proof Verifier",
    description: "Immutable AI accountability layer on Tempo L1. Implements a two-phase commit protocol via AIProofRegistry: Phase 1 — commit a cryptographic hash of the AI's execution plan before any action is taken. Phase 2 — after execution, commit the result hash and link it to the original plan. This creates an unforgeable audit trail proving what the AI intended to do vs. what it actually did. Every proof is timestamped on-chain with block numbers, making AI agent behavior fully auditable and legally defensible.",
    category: "verification",
    skills: JSON.stringify(["proof", "commit", "verify", "ai-proof", "accountability", "two-phase-commit", "audit-trail", "cryptographic-hash", "immutable-record", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "proof-verifier",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "✅",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Proof-Verifier&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 10,
  },
  {
    name: "Allowance Manager",
    description: "Manage ERC20 token allowances for all PayPol contracts. Check, approve, and revoke permissions for NexusV2, ShieldVaultV2, MultisendV2, and StreamV1. On-chain security management.",
    category: "security",
    skills: JSON.stringify(["allowance", "approve", "revoke", "erc20", "security", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "allowance-manager",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔑",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Allowance-Manager&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 1,
    successRate: 97.99,
    avgRating: 4.34,
    ratingCount: 0,
    responseTime: 8,
  },
  {
    name: "Balance Scanner",
    description: "Real-time on-chain portfolio intelligence for any wallet on Tempo L1. Scans all four Tempo stablecoins (AlphaUSD, pathUSD, BetaUSD, ThetaUSD), reads native ETH balance, maps active contract allowances across NexusV2, ShieldVaultV2, MultisendV2, and StreamV1 — and presents a unified portfolio view with USD equivalents. One command gives you complete visibility into any address's financial position on the PayPol network. Fastest response time in the marketplace at under 5 seconds.",
    category: "analytics",
    skills: JSON.stringify(["balance", "portfolio", "scan", "multi-token", "allowance-mapping", "usd-equivalent", "real-time", "wallet-intelligence", "cross-contract", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "balance-scanner",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📋",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Balance-Scanner&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 2,
    successRate: 97.65,
    avgRating: 4.94,
    ratingCount: 1,
    responseTime: 5,
  },
  {
    name: "Fee Collector",
    description: "Collects accumulated platform fees from PayPol smart contracts (NexusV2, MultisendV2, StreamV1). Admin operation that withdraws protocol revenue with real on-chain execution.",
    category: "admin",
    skills: JSON.stringify(["fees", "collect", "withdraw", "revenue", "admin", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "fee-collector",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "💰",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Fee-Collector&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 2,
    successRate: 95.71,
    avgRating: 4.57,
    ratingCount: 1,
    responseTime: 20,
  },
  {
    name: "Escrow Lifecycle",
    description: "Manages NexusV2 escrow job progression — start execution, mark jobs complete, and rate workers. Handles mid-lifecycle steps complementing the Escrow Manager. Real on-chain execution.",
    category: "escrow",
    skills: JSON.stringify(["escrow", "start-job", "complete", "rate", "lifecycle", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "escrow-lifecycle",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔄",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Escrow-Lifecycle&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 1,
    successRate: 95.52,
    avgRating: 4.49,
    ratingCount: 0,
    responseTime: 10,
  },
  {
    name: "Multi Token Sender",
    description: "Send multiple different token types to a single recipient in one operation. AI parses 'send 100 AlphaUSD and 50 BetaUSD to 0x...' and executes each transfer on-chain. Tempo L1.",
    category: "payments",
    skills: JSON.stringify(["multi-token", "transfer", "batch-send", "erc20", "payment", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "multi-token-sender",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "💳",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Multi-Token-Sender&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 2,
    successRate: 99.49,
    avgRating: 4.61,
    ratingCount: 1,
    responseTime: 12,
  },
  {
    name: "Escrow Dispute",
    description: "NexusV2 dispute resolution agent. Raise disputes on active escrows, check timeout status, and claim timed-out refunds. AI-powered dispute management with real on-chain execution.",
    category: "escrow",
    skills: JSON.stringify(["dispute", "timeout", "refund", "nexus", "resolution", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "escrow-dispute",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "⚖️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Escrow-Dispute&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 2,
    successRate: 96.77,
    avgRating: 4.50,
    ratingCount: 1,
    responseTime: 10,
  },
  {
    name: "Stream Inspector",
    description: "Deep on-chain stream analysis for PayPolStreamV1. Reads stream state, milestone statuses, payment progress, and deadline info. Comprehensive stream analytics from Tempo L1.",
    category: "analytics",
    skills: JSON.stringify(["stream", "inspect", "milestone", "analysis", "read", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "stream-inspector",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔎",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Stream-Inspector&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 8,
  },
  {
    name: "Treasury Manager",
    description: "CFO-grade treasury dashboard in a single agent call. Aggregates native ETH holdings, all stablecoin balances, active escrow commitments (NexusV2), pending batch payments (MultisendV2), streaming obligations (StreamV1), AI proof registry stats, and contract allowance exposure — all from live on-chain data. Provides a complete financial health snapshot: total assets, outstanding liabilities, available liquidity, and protocol activity metrics. The command center for any organization managing funds on Tempo L1.",
    category: "analytics",
    skills: JSON.stringify(["treasury", "portfolio", "overview", "financial-health", "liquidity-analysis", "escrow-exposure", "streaming-obligations", "protocol-metrics", "cross-contract-aggregation", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "treasury-manager",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🏛️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Treasury-Manager&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 10,
  },
  {
    name: "Bulk Escrow",
    description: "Batch-create multiple NexusV2 escrow jobs at once. AI parses lists of workers with budgets and creates all escrows sequentially on-chain. Ideal for hiring multiple agents.",
    category: "escrow",
    skills: JSON.stringify(["bulk", "batch-create", "escrow", "nexus", "multi-job", "on-chain"]),
    basePrice: 12,
    nativeAgentId: "bulk-escrow",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📁",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Bulk-Escrow&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 30,
  },
  {
    name: "Multi Token Batch",
    description: "Execute MultisendV2 batch payments with any supported token (AlphaUSD, pathUSD, BetaUSD, ThetaUSD). AI parses token choice and recipient list for gas-efficient on-chain batch transfers.",
    category: "payments",
    skills: JSON.stringify(["batch", "multisend", "multi-token", "bulk-payment", "flexible", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "multi-token-batch",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🎨",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Multi-Token-Batch&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 15,
  },
  {
    name: "Proof Auditor",
    description: "Deep audit of AIProofRegistry on-chain data. Reads total commitments, verification rates, individual proof records, and agent accountability scores. Comprehensive AI proof analytics.",
    category: "verification",
    skills: JSON.stringify(["audit", "proof", "registry", "accountability", "verification", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "proof-auditor",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🧐",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Proof-Auditor&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 8,
  },
  {
    name: "Vault Inspector",
    description: "Inspect ShieldVaultV2 on-chain state — total deposits, commitment records, nullifier checks, and vault balance. Verifies zero-knowledge proof infrastructure on Tempo L1.",
    category: "privacy",
    skills: JSON.stringify(["vault", "inspect", "shield", "zk-state", "commitment", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "vault-inspector",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🕵️",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Vault-Inspector&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 8,
  },
  {
    name: "Gas Profiler",
    description: "Profile gas costs of individual PayPol operations on Tempo L1. Measures real gas usage for transfers, escrows, batch sends, stream operations, and proof commits. Cost optimization tool.",
    category: "analytics",
    skills: JSON.stringify(["gas", "profiler", "cost", "benchmark", "optimization", "on-chain"]),
    basePrice: 3,
    nativeAgentId: "gas-profiler",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "⛽",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Gas-Profiler&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 25,
  },
  {
    name: "Recurring Payment",
    description: "Set up recurring scheduled payments as multiple payment streams on PayPolStreamV1. AI parses payment schedules and creates milestone-based streams for each period. On-chain automation.",
    category: "payments",
    skills: JSON.stringify(["recurring", "schedule", "stream", "subscription", "automated", "on-chain"]),
    basePrice: 10,
    nativeAgentId: "recurring-payment",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🔁",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Recurring-Payment&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 25,
  },
  {
    name: "Contract Reader",
    description: "Read all PayPol smart contract states comprehensively. NexusV2 jobs, MultisendV2 batches, StreamV1 streams, worker ratings, and AI proof stats. Complete on-chain data dashboard.",
    category: "analytics",
    skills: JSON.stringify(["contract", "read", "state", "jobs", "batches", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "contract-reader",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📖",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Contract-Reader&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 10,
  },
  {
    name: "Wallet Sweeper",
    description: "Emergency response agent for rapid asset evacuation. When a wallet is compromised or needs migration, this agent scans all four Tempo stablecoins (AlphaUSD, pathUSD, BetaUSD, ThetaUSD), identifies non-zero balances, and executes sequential transfers to your designated safe address — all in a single operation. Designed for speed: no confirmation delays, no approval prompts, just immediate on-chain transfers. Critical infrastructure for key rotation, wallet migration, and incident response scenarios.",
    category: "security",
    skills: JSON.stringify(["sweep", "emergency", "recovery", "migration", "incident-response", "key-rotation", "multi-token-evacuation", "rapid-execution", "asset-protection", "on-chain"]),
    basePrice: 5,
    nativeAgentId: "wallet-sweeper",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🧹",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Wallet-Sweeper&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 15,
  },
  {
    name: "Escrow Batch Settler",
    description: "Batch settle or refund multiple NexusV2 escrow jobs at once. Process up to 20 job completions in a single operation. AI parses intent and executes real on-chain settlements.",
    category: "escrow",
    skills: JSON.stringify(["batch-settle", "batch-refund", "multi-escrow", "bulk", "settlement", "on-chain"]),
    basePrice: 8,
    nativeAgentId: "escrow-batch-settler",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📑",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Escrow-Batch-Settler&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 20,
  },
  {
    name: "Token Minter",
    description: "Deploy custom ERC20 tokens with fine-grained control. Set name, symbol, decimals, and initial supply. AI parses token parameters and deploys real contracts on Tempo L1.",
    category: "deployment",
    skills: JSON.stringify(["mint", "deploy", "erc20", "custom-token", "create", "on-chain"]),
    basePrice: 10,
    nativeAgentId: "token-minter",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "🏭",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Token-Minter&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 30,
  },
  {
    name: "Chain Monitor",
    description: "Monitor Tempo L1 chain health and activity. Tracks block times, transaction throughput, contract activity counters (jobs, batches, streams, proofs), and network health diagnostics.",
    category: "analytics",
    skills: JSON.stringify(["monitor", "chain-health", "block-time", "throughput", "diagnostics", "on-chain"]),
    basePrice: 2,
    nativeAgentId: "chain-monitor",
    ownerWallet: PAYPOL_PLATFORM_WALLET,
    avatarEmoji: "📡",
    avatarUrl: "https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Chain-Monitor&backgroundColor=1e293b",
    isVerified: true,
    totalJobs: 0,
    successRate: 100,
    avgRating: 5,
    ratingCount: 0,
    responseTime: 8,
  },
];

async function main() {
  console.log("🤖 Seeding Agent Marketplace (32 on-chain agents)...\n");

  for (const agent of agents) {
    // Upsert by name - allows re-running seed to update existing agents
    const upserted = await prisma.marketplaceAgent.upsert({
      where: { name: agent.name },
      create: agent,
      update: {
        description: agent.description,
        category: agent.category,
        skills: agent.skills,
        basePrice: agent.basePrice,
        nativeAgentId: (agent as any).nativeAgentId ?? null,
        ownerWallet: agent.ownerWallet,
        avatarEmoji: agent.avatarEmoji,
        avatarUrl: (agent as any).avatarUrl ?? null,
        isVerified: agent.isVerified,
        totalJobs: agent.totalJobs,
        successRate: agent.successRate,
        avgRating: agent.avgRating,
        ratingCount: agent.ratingCount,
        responseTime: agent.responseTime,
      },
    });
    console.log(`  ✅ ${agent.avatarEmoji} ${upserted.name} (${agent.category})`);
  }

  const count = await prisma.marketplaceAgent.count();
  console.log(`\n✨ Done! ${count} agents registered in marketplace.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
