// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title AgtFi Compliance Registry
 * @notice On-chain registry for ZK compliance certificates
 * @dev Verifies PLONK proofs that an address:
 *   1. Is NOT on the OFAC sanctions list (SMT non-inclusion proof)
 *   2. Transaction amount < AML threshold
 *   3. 30-day cumulative volume < AML threshold
 *
 * Architecture:
 *   - Trusted operator publishes sanctions tree root on-chain
 *   - Agents generate compliance proofs locally via Circom circuit
 *   - Proofs are verified on-chain → compliance certificate stored
 *   - Any protocol can query: "Is this commitment compliant?"
 *
 * This is the first ZK compliance layer for agent payments.
 * No other protocol (x402, MPP, ACP, AP2) has this capability.
 */

interface IComplianceVerifier {
    function verifyProof(
        uint256[24] calldata _proof,
        uint256[4] calldata _pubSignals
    ) external view returns (bool);
}

contract ComplianceRegistry {

    /*//////////////////////////////////////////////////////////////
                            STATE
    //////////////////////////////////////////////////////////////*/

    /// @notice The PLONK verifier contract (auto-generated by snarkjs)
    IComplianceVerifier public immutable verifier;

    /// @notice Contract owner (can update sanctions root)
    address public owner;

    /// @notice Current OFAC sanctions Merkle tree root
    uint256 public sanctionsRoot;

    /// @notice Timestamp of last sanctions root update
    uint256 public sanctionsRootUpdatedAt;

    /// @notice AML threshold for single transaction (e.g., $10,000 * 1e6)
    uint256 public amountThreshold;

    /// @notice AML threshold for 30-day cumulative volume
    uint256 public volumeThreshold;

    /// @notice Maximum age of a compliance certificate (seconds)
    uint256 public certificateMaxAge;

    /// @notice Fee per proof verification (in wei, 0 = free)
    uint256 public proofFee;

    /// @notice Total fees collected
    uint256 public totalFeesCollected;

    /// @notice Compliance certificate for a commitment
    struct ComplianceCertificate {
        uint256 sanctionsRoot;       // Which sanctions root was used
        uint256 amountThreshold;     // What threshold was checked
        uint256 volumeThreshold;     // What volume limit was checked
        uint256 issuedAt;            // Block timestamp of verification
        uint256 blockNumber;         // Block number of verification
        bool    valid;               // Is certificate active
    }

    /// @notice commitment => ComplianceCertificate
    mapping(uint256 => ComplianceCertificate) public certificates;

    /// @notice Total certificates issued
    uint256 public totalCertificates;

    /// @notice Total successful verifications
    uint256 public totalVerified;

    /// @notice commitment => revoked
    mapping(uint256 => bool) public revoked;


    /*//////////////////////////////////////////////////////////////
                            EVENTS
    //////////////////////////////////////////////////////////////*/

    event SanctionsRootUpdated(uint256 indexed newRoot, uint256 timestamp);
    event ThresholdsUpdated(uint256 amountThreshold, uint256 volumeThreshold);
    event ComplianceCertified(
        uint256 indexed commitment,
        uint256 sanctionsRoot,
        uint256 amountThreshold,
        uint256 volumeThreshold,
        uint256 timestamp
    );
    event CertificateRevoked(uint256 indexed commitment, string reason);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);


    /*//////////////////////////////////////////////////////////////
                            MODIFIERS
    //////////////////////////////////////////////////////////////*/

    modifier onlyOwner() {
        require(msg.sender == owner, "ComplianceRegistry: not owner");
        _;
    }


    /*//////////////////////////////////////////////////////////////
                            CONSTRUCTOR
    //////////////////////////////////////////////////////////////*/

    constructor(
        address _verifier,
        uint256 _sanctionsRoot,
        uint256 _amountThreshold,
        uint256 _volumeThreshold,
        uint256 _certificateMaxAge
    ) {
        verifier = IComplianceVerifier(_verifier);
        owner = msg.sender;
        sanctionsRoot = _sanctionsRoot;
        sanctionsRootUpdatedAt = block.timestamp;
        amountThreshold = _amountThreshold;
        volumeThreshold = _volumeThreshold;
        certificateMaxAge = _certificateMaxAge;

        emit SanctionsRootUpdated(_sanctionsRoot, block.timestamp);
        emit ThresholdsUpdated(_amountThreshold, _volumeThreshold);
    }


    /*//////////////////////////////////////////////////////////////
                            CORE: Verify & Certify
    //////////////////////////////////////////////////////////////*/

    /**
     * @notice Submit a ZK compliance proof for verification
     * @param _proof PLONK proof (24 uint256 elements)
     * @param _pubSignals Public signals: [sanctionsRoot, commitment, amountThreshold, volumeThreshold]
     * @return certificateValid true if proof verified and certificate issued
     *
     * The proof demonstrates:
     *   - Prover knows an address that is NOT in the sanctions tree
     *   - The transaction amount is below the AML threshold
     *   - The 30-day cumulative volume is below the AML threshold
     *   - Without revealing the actual address, amount, or volume
     */
    function verifyCertify(
        uint256[24] calldata _proof,
        uint256[4] calldata _pubSignals
    ) external payable returns (bool certificateValid) {
        require(msg.value >= proofFee, "ComplianceRegistry: insufficient fee");
        if (proofFee > 0) totalFeesCollected += proofFee;

        // Refund excess fee
        if (msg.value > proofFee) {
            (bool refundOk, ) = msg.sender.call{value: msg.value - proofFee}("");
            require(refundOk, "ComplianceRegistry: refund failed");
        }

        uint256 proofSanctionsRoot = _pubSignals[0];
        uint256 commitment = _pubSignals[1];
        uint256 proofAmountThreshold = _pubSignals[2];
        uint256 proofVolumeThreshold = _pubSignals[3];

        // Validate public signals match current state
        require(
            proofSanctionsRoot == sanctionsRoot,
            "ComplianceRegistry: sanctions root mismatch"
        );
        require(
            proofAmountThreshold == amountThreshold,
            "ComplianceRegistry: amount threshold mismatch"
        );
        require(
            proofVolumeThreshold == volumeThreshold,
            "ComplianceRegistry: volume threshold mismatch"
        );
        require(!revoked[commitment], "ComplianceRegistry: commitment revoked");

        // Verify the PLONK proof on-chain
        bool proofValid = verifier.verifyProof(_proof, _pubSignals);
        require(proofValid, "ComplianceRegistry: invalid ZK proof");

        // Issue compliance certificate
        certificates[commitment] = ComplianceCertificate({
            sanctionsRoot: sanctionsRoot,
            amountThreshold: amountThreshold,
            volumeThreshold: volumeThreshold,
            issuedAt: block.timestamp,
            blockNumber: block.number,
            valid: true
        });

        totalCertificates++;
        totalVerified++;

        emit ComplianceCertified(
            commitment,
            sanctionsRoot,
            amountThreshold,
            volumeThreshold,
            block.timestamp
        );

        return true;
    }


    /*//////////////////////////////////////////////////////////////
                            QUERY: Check compliance status
    //////////////////////////////////////////////////////////////*/

    /**
     * @notice Check if a commitment has a valid compliance certificate
     * @param commitment The compliance commitment to check
     * @return isCompliant true if certificate exists, is valid, and not expired
     */
    function isCompliant(uint256 commitment) external view returns (bool) {
        ComplianceCertificate memory cert = certificates[commitment];

        if (!cert.valid) return false;
        if (revoked[commitment]) return false;
        if (block.timestamp > cert.issuedAt + certificateMaxAge) return false;
        if (cert.sanctionsRoot != sanctionsRoot) return false;

        return true;
    }

    /**
     * @notice Get full certificate details
     * @param commitment The compliance commitment
     * @return cert The compliance certificate struct
     * @return expired Whether the certificate has expired
     * @return currentRoot Whether the certificate uses current sanctions root
     */
    function getCertificate(uint256 commitment)
        external view
        returns (
            ComplianceCertificate memory cert,
            bool expired,
            bool currentRoot
        )
    {
        cert = certificates[commitment];
        expired = block.timestamp > cert.issuedAt + certificateMaxAge;
        currentRoot = cert.sanctionsRoot == sanctionsRoot;
    }


    /*//////////////////////////////////////////////////////////////
                            ADMIN: Manage sanctions & thresholds
    //////////////////////////////////////////////////////////////*/

    /**
     * @notice Update the OFAC sanctions tree root
     * @dev Should be called daily by the trusted operator
     * @param _newRoot New Merkle tree root containing sanctioned addresses
     */
    function updateSanctionsRoot(uint256 _newRoot) external onlyOwner {
        require(_newRoot != 0, "ComplianceRegistry: root cannot be zero");
        sanctionsRoot = _newRoot;
        sanctionsRootUpdatedAt = block.timestamp;
        emit SanctionsRootUpdated(_newRoot, block.timestamp);
    }

    /**
     * @notice Update AML thresholds
     * @param _amountThreshold New per-transaction threshold
     * @param _volumeThreshold New 30-day volume threshold
     */
    function updateThresholds(
        uint256 _amountThreshold,
        uint256 _volumeThreshold
    ) external onlyOwner {
        require(_amountThreshold > 0 && _volumeThreshold > 0, "ComplianceRegistry: thresholds must be positive");
        amountThreshold = _amountThreshold;
        volumeThreshold = _volumeThreshold;
        emit ThresholdsUpdated(_amountThreshold, _volumeThreshold);
    }

    /**
     * @notice Update certificate max age
     * @param _maxAge New max age in seconds
     */
    function setCertificateMaxAge(uint256 _maxAge) external onlyOwner {
        require(_maxAge >= 3600, "ComplianceRegistry: min 1 hour");
        certificateMaxAge = _maxAge;
    }

    /**
     * @notice Revoke a compliance certificate (e.g., newly sanctioned address)
     * @param commitment The commitment to revoke
     * @param reason Human-readable reason for revocation
     */
    function revokeCertificate(uint256 commitment, string calldata reason) external onlyOwner {
        certificates[commitment].valid = false;
        revoked[commitment] = true;
        emit CertificateRevoked(commitment, reason);
    }

    /**
     * @notice Transfer ownership
     * @param newOwner The new owner address
     */
    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "ComplianceRegistry: zero address");
        emit OwnershipTransferred(owner, newOwner);
        owner = newOwner;
    }

    /**
     * @notice Set proof verification fee
     * @param _fee Fee in wei per proof verification
     */
    function setProofFee(uint256 _fee) external onlyOwner {
        proofFee = _fee;
    }

    /**
     * @notice Withdraw collected fees
     */
    function withdrawFees() external onlyOwner {
        uint256 balance = address(this).balance;
        require(balance > 0, "ComplianceRegistry: no fees to withdraw");
        (bool success, ) = payable(owner).call{value: balance}("");
        require(success, "ComplianceRegistry: withdraw failed");
    }


    /*//////////////////////////////////////////////////////////////
                            VIEW: Statistics
    //////////////////////////////////////////////////////////////*/

    function getStats() external view returns (
        uint256 _totalCertificates,
        uint256 _totalVerified,
        uint256 _sanctionsRoot,
        uint256 _sanctionsRootUpdatedAt,
        uint256 _amountThreshold,
        uint256 _volumeThreshold,
        uint256 _certificateMaxAge
    ) {
        return (
            totalCertificates,
            totalVerified,
            sanctionsRoot,
            sanctionsRootUpdatedAt,
            amountThreshold,
            volumeThreshold,
            certificateMaxAge
        );
    }
}
