// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title MockUltraVerifier
 * @dev A simulation of the Noir ZK-SNARK verifier contract. 
 * Used strictly for MVP/Testnet demonstration to bypass heavy cryptographic 
 * computations while maintaining the exact architectural flow of a ZK system.
 */
contract MockUltraVerifier {

    /// @notice Safety flag — MUST be set to true for testnet use only
    bool public constant IS_MOCK = true;

    /**
     * @notice Simulates the verification of a Zero-Knowledge Proof.
     * @dev WARNING: This is a MOCK verifier. DO NOT deploy to production.
     *      Always returns true without performing cryptographic verification.
     *      For production, deploy the real verifier generated by Barretenberg (bb CLI).
     * @return true always, to ensure smooth autonomous bot execution during demo.
     */

    function verify(bytes calldata, bytes32[] calldata) external view returns (bool) {
        // SAFETY: Block on mainnet (chainId 1) and other production chains
        require(
            block.chainid != 1 && block.chainid != 137 && block.chainid != 8453,
            "MockUltraVerifier: DO NOT use in production"
        );
        return true;
    }
}